### ISSUE TITLE
楼主好人，经过测试了不？封号封的人心惶惶

### ISSUE THREAD

**Issue by wz960413** [studyhelperhelper/studyhelper#1]

**Comment by wz960413** [comment]
安装时显示解析包时出现问题

**Comment by studyhelperhelper** [comment]
百度上搜索的结果：
安卓手机解析包时出现问题的解决方法：
1、安卓apk程序解析包出现问题的话，可能是由于你下载的apk程序本身就有问题，程序的压缩包可能在下载过程中被损坏了，建议请重新下载一次。
2、如果重新下载也解决不了安卓解析包出现问题的话，很大一个可能就是在于你的手机的配置参数不支持这款软件，举个例子吧，如果一款apk程序的系统版本要求在安卓2.2以上，而你的手机则是安卓2.1系统，就会出现“解析包时出现问题”这样的解析错误。
3、还有一种可能是由于RE文件管理设置的缘故，进入RE管理器——设置——一键设置——主文件夹选项，有的朋友反映如果将其设置成“sdcard\ ”就会出现“解析包出现问题”的错误提示，而如果将其设置“\ ”就可以成功安装，建议诸位可以试试！

你可以再下载一次试试，最好下载rar包。
同时我看看我要求的安卓版本，看看能不能降低一下要求。
