### ISSUE TITLE
小米8挑战答题总是错误

### ISSUE THREAD

**Issue by ouyangmland** [studyhelperhelper/studyhelper#10]
挑战答题经常答第一题就错误。

**Comment by studyhelperhelper** [comment]
刚发现这个问题，应该是题库未拷贝到本地，请卸载应用重新安装，安装过程中请选择允许存储。
另外，请关闭自动清理等程序，防止将题库清除 了。目前发现华为的手机自动清理功能会清除题库。

**Comment by ouyangmland** [comment]
好的，知道了，感谢大佬回答

> 刚发现这个问题，应该是题库未拷贝到本地，请卸载应用重新安装，安装过程中请选择允许存储。
> 另外，请关闭自动清理等程序，防止将题库清除 了。目前发现华为的手机自动清理功能会清除题库。

好的感谢大佬解答。
