### ISSUE TITLE
请问作者用的什么手机呀

### ISSUE THREAD

**Issue by gh4492** [studyhelperhelper/studyhelper#106]
请问作者用的什么手机呀？什么系统我的手机是一加1，lineageOS安卓7.1.2，只有最开始的版本（那时刷的系统版本是lineageOS安卓9.0）使用正常过，现在从来就没正常过

**Comment by studyhelperhelper** [comment]
我用的华为mate9，mate10，P30等机型都没问题。

**Comment by PS0123456** [comment]
> 我用的华为mate9，mate10，P30等机型都没问题。
大佬，你用华为，不怕被上报这软件么？

**Comment by 85524365** [comment]
> > 我用的华为mate9，mate10，P30等机型都没问题。
> > 大佬，你用华为，不怕被上报这软件么？

用什么不怕呀？
