### ISSUE TITLE
大神！@能否直接提供一个autojs的自适应分辨率的study脚本

### ISSUE THREAD

**Issue by wangfenger** [studyhelperhelper/studyhelper#107]
大神！能否直接提供一个autojs的自适应分辨率的study脚本

**Comment by studyhelperhelper** [comment]
不是autoJS编制的

**Comment by wangfenger** [comment]
大神能否用AutojS写个自动阅读文章和视频脚本，不需要其它功能发自我的华为手机-------- 原始邮件 --------主题：Re: [studyhelperhelper/studyhelper] 大神！@能否直接提供一个autojs的自适应分辨率的study脚本 (#107)发件人：studyhelperhelper 收件人：studyhelperhelper/studyhelper 抄送：wangfenger ,Author 不是autoJS编制的



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/studyhelperhelper/studyhelper/issues/107?email_source=notifications\u0026email_token=AEZD5P4VFANYJOKLGNIS6U3Q2CGOVA5CNFSM4J6QISQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHQZP6A#issuecomment-568432632",

"url": "https://github.com/studyhelperhelper/studyhelper/issues/107?email_source=notifications\u0026email_token=AEZD5P4VFANYJOKLGNIS6U3Q2CGOVA5CNFSM4J6QISQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHQZP6A#issuecomment-568432632",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
