### ISSUE TITLE
众多模拟器无法安装~~求大神支招一下

### ISSUE THREAD

**Issue by xiaoxiongke** [studyhelperhelper/studyhelper#108]
谢谢了  很多模拟器都试了一下 安装不了

**Comment by 85524365** [comment]
如果支持安装装模拟器，会让高层注意。风险太大。最终会杀鸡取卵，都没得玩！！

建议作者一定不要支持模拟器，低调行事，皆大欢喜。

**Comment by xiaoxiongke** [comment]
自己已经解决了。。要安装在7.0以后的模拟器系统才能安装。。。
