### ISSUE TITLE
谢谢作者，顺便请教各位

### ISSUE THREAD

**Issue by kentmay** [studyhelperhelper/studyhelper#11]
在samsung S7e 运行时始终在主页和个人信息页面来回跳转，请教大家怎么解决？

**Comment by studyhelperhelper** [comment]
说明点击到“我的”界面后，未找到 学习积分  的按钮。程序第一步设置的是先去看看已经学习了多少分了。看不到不罢休。请重启试试，请安装最新版本，也可能是网络环境较差，学习强国未将该节点加载上，我试试在新版本中把延时调长一点。

**Comment by kentmay** [comment]
> 说明点击到“我的”界面后，未找到 学习积分 的按钮。程序第一步设置的是先去看看已经学习了多少分了。看不到不罢休。请重启试试，请安装最新版本，也可能是网络环境较差，学习强国未将该节点加载上，我试试在新版本中把延时调长一点。

谢谢您回复，我把学习强国app更新到最新版后可以开始学习了。这次是卡在发表文章观点那里了。

**Comment by studyhelperhelper** [comment]
是不是和卡在填空那里的是一个问题，怀疑未找到输入框的节点。晚上有空再研究一下。
