### ISSUE TITLE
有道题好像会出现错误！

### ISSUE THREAD

**Issue by huuunm** [studyhelperhelper/studyhelper#111]
题库中“以下不属于二十四史的是”题库中答案是正确的“清史”，但是会选到错误答案“史记”。

**Comment by lnxglycyq1971** [comment]
我印象中这道题有两个一模一样的题目，但是答案列表并不一样，一个的正确答案是《清史》，另一个的正确答案是《左传》，代码没法区分开来，晕。

**Comment by 85524365** [comment]
楼主真细心。  不属于24史的有   左传 ， 我也遇到了。
