### ISSUE TITLE
反馈每日答题bug

### ISSUE THREAD

**Issue by ouyangmland** [studyhelperhelper/studyhelper#112]
每日答题，只要答错了题，就会去查看屏幕上正确答案的解析。如果答案的解析超过手机屏幕显示，软件也会自动下拉一下，当然以上情形并不是bug。紧接着bug问题就会出现。屏幕下拉查看解析后，屏幕又会出现自动右滑的操作，因为屏幕右滑导致出现返回上一题的情况或者出现退出每日答题的提示框（退出每日答题提示框的出现是第一题答错的情况下）。这个情况已经出现在作者前几次更新的版本都有这个问题。
我自己的设备是小米8，按道理应该不是屏幕适配问题导致出现这样的bug。这个bug可以复现。只要每日答题答错必出现上述情形。

**Comment by studyhelperhelper** [comment]
请不要使用手势导航。

**Comment by studyhelperhelper** [comment]
谢谢反馈，下次更新的时候会改一下，再离边缘远一点，防止触发手势导航的返回。目前如果非要使用这个APP的话请先别用手势导航了吧。
