### ISSUE TITLE
求更新，谢谢

### ISSUE THREAD

**Issue by szxyes** [studyhelperhelper/studyhelper#118]
老哥，求更新，甚为感谢。

**Comment by hbjzhbjz** [comment]
怎么不能安装？请问

**Comment by szxyes** [comment]
> 怎么不能安装？请问

最低版本要安卓7安卓7以下解析包错误

**Comment by hbjzhbjz** [comment]
谢谢

szxyes <notifications@github.com> 于 2020年3月7日周六 15:56写道：
