### ISSUE TITLE
大佬，今天不能运行了

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#123]
再次感恩大佬。
现在运行卡住了，貌似新闻联播找不到了，求更新。

**Comment by 85524365** [comment]
每一次都怀着感恩的心感谢大神。希望大神能陪伴我们与天地同寿，嘿嘿。

旧版本开启刷题库按钮后，发现题库整个题库失效了，
貌似：
1、刷题库按钮会把原来的题库清理掉
2、然后新的题库只保存一部分正确答案
3、错误的题 没有保存下正确答案，仅保存下了wrong的。

建议大佬能给个手动增加修改新题库的选项，

希望软件越来越完美，大佬越来越srong。

**Comment by 20057842** [comment]
你试下清除所有数据，我试过有些问题用清除所有数据就解决了，现在只有每日功能是失效的，所以手动更加快（收、发、分、本地、每日）。

**Comment by 20057842** [comment]
感谢，谢谢大佬的开发。

**Comment by 85524365** [comment]
> 你试下清除所有数据，我试过有些问题用清除所有数据就解决了，现在只有每日功能是失效的，所以手动更加快（收、发、分、本地、每日）。

谢谢，希望大佬能更新一下

**Comment by 85524365** [comment]
感恩大神。
目前每日答题出现了新题目，出现的填空题是多个空格，导致软件卡住运行不下去。
