### ISSUE TITLE
大神离开的日子里，好难熬，望安康

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#126]
大神，这些日子度日如年啊。
好担心，希望大神阖家安康，希望网友们安康。
1、现在答题的填空题出现了很多变化，尤其是一道题出现2个填空，而且有的两个横线之间还有文字和标点，到这时候就卡住了。
2、自动记录到题库中的选项出错，导致挑战答题和每日答题进行不下去。
期盼盼更新😭

**Comment by studyhelperhelper** [comment]
正在正常使用，目前2.10.0及2.9.2版本学习强国都好用。你自己检查一下版本。
我发现真有大神，我自己重来没出过学习助手2.10.0—1版本，竟然真有人反编译后盗取发布到别的平台。在此声明一下，github是唯一发布平台，目前学习助手最新版本仍然是2.9.2—1。请使用正确版本后反馈使用情况。

**Comment by 85524365** [comment]
看到大神露面回复，大家都放心啦。好人一生平安！健康就好。
程序确实能运行。
不过有时卡住了，需要退出来，重新打开几次才好。
