### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by yishuihanbuhan** [studyhelperhelper/studyhelper#127]
每日答题和挑战答题均不能正常使用了

**Comment by studyhelperhelper** [comment]
注意版本，目前学习助手最新版本是2.9.2—1。对应学习强国版本2.9.2或者2.10.0都可以使用。如果你的学习强国又有新版本了，请安装低版本使用。

**Comment by yishuihanbuhan** [comment]
目前在用的是2.10.0，我换成2.9.2明天试一下，谢谢回复发自我的华为手机-------- 原始邮件 --------发件人： studyhelperhelper <notifications@github.com>日期： 2020年3月29日周日 上午10:37收件人： studyhelperhelper/studyhelper <studyhelper@noreply.github.com>抄送： yishuihanbuhan <187044209@qq.com>, Author <author@noreply.github.com>主    题： Re: [studyhelperhelper/studyhelper] 求更新 (#127)

注意版本，目前学习助手最新版本是2.9.2—1。对应学习强国版本2.9.2或者2.10.0都可以使用。如果你的学习强国又有新版本了，请安装低版本使用。

**Comment by studyhelperhelper** [comment]
再次声明学习助手从未发布2.10.0—1版本，github 是唯一发布平台。

**Comment by HaDX-MLL** [comment]
无法正常使用的主要还是系统问题吧，我这边一台lineageos16安卓9，全程不停顿的，只是极少数每日答题题目无法完成，重进一下就行。另一台OPPO colorOS安卓8.1，会卡在各种地方，基本上无法正常完成所有的。

**Comment by HaDX-MLL** [comment]
今天强制要求更新2.11.1了，大佬求更新_(:3」∠)_

**Comment by huuunm** [comment]
同上！现在会要求强制更新，但是现在最新版本好像也能正常运行。

**Comment by urbanpauper** [comment]
求大神更新，答题功能现在不太好用了，需要手动答题。

**Comment by 20057842** [comment]
估计QG当时没考虑有黑白页面，今天更新后立马就全黑了。

**Comment by aoyoo111** [comment]
@urbanpauper 答题手动答题吧，我从来都是这样，每天手动2分钟左右搞定，其他费时的用自动挂机

**Comment by szsyzx** [comment]
大神有空可以更新下不，软件强制更新无法使用了！辛苦大神了

**Comment by HaDX-MLL** [comment]
虽然强制更新了，但是各功能使用没问题，也就那天因为页面比较特别的关系无法正常使用

**Comment by tomato231** [comment]
大神，题库怎么更新？

**Comment by tomato231** [comment]
挑战答题好多新题，如何更新题库

**Comment by urbanpauper** [comment]
> 大神有空可以更新下不，软件强制更新无法使用了！辛苦大神了

其实现在你又可以安装回旧版本了。

**Comment by studyhelperhelper** [comment]
遇到大面积答错题的情况，请卸载APP，用文件管理器在跟目录找到com. study.helper文件夹，删除。然后重装。
