### ISSUE TITLE
完美的软件，威武的大神

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#128]
学习强国多次升级了，每次升级大家都是提心掉蛋，然而大神的软件我自岿然不动，依然好用，实在牛叉！！膜拜！哈哈哈！真想给大神送上个美妞，嘿嘿嘿。
             然后给大神提点建议哈，希望软件更完美：
            1、填空题：有的不止一个空格，个别的空格之间还有标点和文字，这时候就卡住了，下面的项目也不能进行了。希望下一版本如果没有题库，能直接跳过去，答其他的项目。
            2、题库常失效：
感觉是因为新题保存后，保存的格式可能不正确，导致题库失效。
            3、建议题库中的题干等去掉标点符号，这样无论怎么变化，搜索起来也容易。
           
    当然我们提建议简单，大神就要费心了，提建议的时候也很忐忑，不想给大神增加负担，希望大神

无视。

**Comment by studyhelperhelper** [comment]
遇到大面积答错题，像题库失效的样子的情况，请卸载APP，用文件管理器在跟目录找到com. study.helper文件夹，删除。然后重装。填空已经考虑多个空的问题，我自己测试未发现卡住现象。

**Comment by 85524365** [comment]
> 遇到大面积答错题，像题库失效的样子的情况，请卸载APP，用文件管理器在跟目录找到com. study.helper文件夹，删除。然后重装。填空已经考虑多个空的问题，我自己测试未发现卡住现象。

感谢大神回复，那可能是我自己修改的题库有问题，导致卡住

**Comment by noway2014** [comment]
thx
