### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by Janson88** [studyhelperhelper/studyhelper#129]
题库识别失败，求更新

**Comment by 85524365** [comment]
卸载后重新安装一下

**Comment by 85524365** [comment]
卸载后重新安装一下

**Comment by Janson88** [comment]
好的，谢谢大佬

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "85524365"<notifications@github.com&gt;; 
发送时间: 2020年4月12日(星期天) 下午5:58
收件人: "studyhelperhelper/studyhelper"<studyhelper@noreply.github.com&gt;; 
抄送: "深深情眸含泪别"<2274844404@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [studyhelperhelper/studyhelper] 求更新 (#129)





 
卸载后重新安装一下

**Comment by Janson88** [comment]
卸载后重装填空题有的做不了，一直卡在那，重启也一样，是题库不完善的原因吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "85524365"<notifications@github.com&gt;; 
发送时间: 2020年4月12日(星期天) 下午5:58
收件人: "studyhelperhelper/studyhelper"<studyhelper@noreply.github.com&gt;; 
抄送: "深深情眸含泪别"<2274844404@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [studyhelperhelper/studyhelper] 求更新 (#129)





 
卸载后重新安装一下
