### ISSUE TITLE
软件在删除评论后就会停止

### ISSUE THREAD

**Issue by ouyangmland** [studyhelperhelper/studyhelper#13]
软件自动发表评论然后删除评论，删除评论后就不再进行任何操作，好像有点bug。我试了不是机型问题，我用了两种不一样的机型测试都是这样。

**Comment by ohhhyy** [comment]
同样问题 MI6 MIUI10

**Comment by studyhelperhelper** [comment]
我在华为手机上运行正常，有空我再看看代码。请先更新最新版本，新版右上角菜单设置中可以先屏蔽评论功能，先确保程序能走完。

**Comment by zsdw52** [comment]
> 我在华为手机上运行正常，有空我再看看代码。请先更新最新版本，新版右上角菜单设置中可以先屏蔽评论功能，先确保程序能走完。

请问下，华为开启无障碍运行软件以后，一会软件就自动停止，再看无障碍已经被自动关闭，请问这个问题能解决吗，一直如此。程序没有退出。

**Comment by studyhelperhelper** [comment]
我没碰到过这情况，查查哪里有自动关闭的设置。

**Comment by vincentmomo** [comment]
这个不是bug，是因为新版的学习强国添加了评论必须拖到文章最下面才可以的问题，点开文章拖到最下边应该就可以解决这个问题了。

**Comment by kentmay** [comment]
删除评论后，程序停止。1.3.6版也有此现象。

**Comment by studyhelperhelper** [comment]
有空重写一下

**Comment by 85524365** [comment]
1.4.1也是这个样子，发表一个观点，删除之后，就卡住不动了，第二个观点也不能发表。
