### ISSUE TITLE
老大，貌似填空题还是有卡住

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#131]
大神，2.12.0-1好极啦。感激不尽！
唯一缺憾就是在遇到填空时，如果是2个空格，2个空格间有汉字（例如：和）或标点符号或一句话，答题就卡住了，不再往下进行。
手机是华为p9,系统安卓8.0
华为7s，系统安卓9.0

**Comment by studyhelperhelper** [comment]
已更新。

**Comment by 85524365** [comment]
老大仁义，感激不尽

**Comment by szsyzx** [comment]
@studyhelperhelper 非常感谢老大

**Comment by szsyzx** [comment]
@studyhelperhelper 老大有电报吗，QQ微信不能建群我们在电报上建立个吧

**Comment by YK202** [comment]
@studyhelperhelper 老大 怎么下载不了啊？
