### ISSUE TITLE
可以用MIUI 12的小窗模式挂机吗？

### ISSUE THREAD

**Issue by luo-chuan** [studyhelperhelper/studyhelper#134]
![图片](https://wx1.sinaimg.cn/large/6a815515ly1ge8bedbqosg20u00u0kjm.gif)  
见这个网页倒数第二张图 https://www.ithome.com/0/484/703.htm

**Comment by shanghai337** [comment]
你的是小米10吗？

**Comment by luo-chuan** [comment]
> 你的是小米10吗？

没有。我就随便问问，如果可以才换小米。
