### ISSUE TITLE
模拟器答不了题 会出错

### ISSUE THREAD

**Issue by yooaiyim** [studyhelperhelper/studyhelper#140]
有点麻烦哈  ：）  另外  题库 没找到在哪下载 TT

**Comment by 85524365** [comment]
用模拟器大大增加封号的风险

**Comment by yooaiyim** [comment]
晕。。。 我用了半年了&nbsp; 吓&nbsp; 赶紧换手机&nbsp; 谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "85524365"<notifications@github.com&gt;; 
发送时间: 2020年5月24日(星期天) 晚上6:34
收件人: "studyhelperhelper/studyhelper"<studyhelper@noreply.github.com&gt;; 
抄送: "白色猎人"<yooaiyim@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [studyhelperhelper/studyhelper] 模拟器答不了题 会出错 (#140)





 
用模拟器大大增加封号的风险
