### ISSUE TITLE
大神建议把app里的下载接口关闭。

### ISSUE THREAD

**Issue by nysamurai** [studyhelperhelper/studyhelper#149]
大神建议把app里的下载接口关闭。

**Comment by 85524365** [comment]
为什么？难到目的为了只给你一个人使用吗？

**Comment by nysamurai** [comment]
你误会了，我是怕这么好的软件被封，下载地址容易被封

________________________________
发件人: 85524365 <notifications@github.com>
发送时间: 2020年6月16日 14:17
收件人: studyhelperhelper/studyhelper <studyhelper@noreply.github.com>
抄送: nysamurai <nysamurai@msn.cn>; Author <author@noreply.github.com>
主题: Re: [studyhelperhelper/studyhelper] 大神建议把app里的下载接口关闭。 (#149)


为什么？难到目的为了只给你一个人使用吗？

―

**Comment by 85524365** [comment]
好人一生平安

**Comment by jiajing73** [comment]
我觉得这个助手没有已经404的懒人学习好用。

**Comment by 7300319** [comment]
> 我觉得这个助手没有已经404的懒人学习好用。

可惜啊
