### ISSUE TITLE
感谢大佬工具但是有几个问题

### ISSUE THREAD

**Issue by sbqgreat** [studyhelperhelper/studyhelper#15]
1.有时候突然到哪一部就不动了 进程后台给常驻权限了
2.到填空题不会答题 进程后面走不完
3.选择题十道题左右就跟不上倒计时了
再次感谢

**Comment by studyhelperhelper** [comment]
挑战答题如果超时，是故意的，准备停止。默认设置答题10左右，如果想多答题，可以在设置里面改。每日答题应该不会出现问题，请再多试几次，不行先屏蔽掉。

**Comment by sbqgreat** [comment]
非常感谢 填空题的问题呢  屏蔽我可以尝试一下

**Comment by studyhelperhelper** [comment]
填空题我的华为手机运行正常，不会答的题会胡编个答案，然后提交，下次就会正确回答了。你说的没碰到过，方便不方便说一下手机型号版本，是填写上内容了不提交，还是直接不填写内容？

**Comment by sbqgreat** [comment]
不填写内容 到填空题就中断 不知道是输入法问题还是其他
meizu 16p 输入法讯飞

**Comment by studyhelperhelper** [comment]
思路是这样，和我们自己操作手机一样，先点击填空的输入框，点击后应该是呼出输入键盘了，然后生成文字，然后复制到填空里面。如果你是走到呼出键盘，未填入内容说明复制不成功，不知道是不是输入法的问题。如果直接未呼出键盘，说明未点击到填空的输入框。难道每个手机输入框的ID还不同？

**Comment by kentmay** [comment]
发表文章评论时，能呼出键盘，输入框内没有内容，然后程序停止。

Samsung S7E ，android 8.0 ， 讯飞输入法。

**Comment by studyhelperhelper** [comment]
知道了，下次升级修正吧。先屏蔽掉，手动发表评论吧。

**Comment by studyhelperhelper** [comment]
换个输入法试试？

**Comment by sbqgreat** [comment]
输入法换过了 能呼出键盘 输入框没有内容 程序停止同上 感觉是不能输入的问题

**Comment by studyhelperhelper** [comment]
测试一下1.3.5版本吧。
