### ISSUE TITLE
MIUI 12 安卓10系统 一直在我的界面 --学习积分界面来回切换

### ISSUE THREAD

**Issue by szsyzx** [studyhelperhelper/studyhelper#155]
MIUI12 安卓10系统 一直在我的界面 --学习积分界面来回切换
https://ftp.bmp.ovh/imgs/2020/08/2a3dbe02613e84b4.jpg

https://ftp.bmp.ovh/imgs/2020/08/251a1876b3a2f0cb.jpg

不知道是我个例还是都这个样子

**Comment by szsyzx** [comment]
[https://ftp.bmp.ovh/imgs/2020/08/251a1876b3a2f0cb.jpg](url)

**Comment by includewins0ck2** [comment]
我也是今天刚更新，也是这个bug

**Comment by szsyzx** [comment]
坐等老大更新了

**Comment by urbanpauper** [comment]
也是这个毛病

**Comment by wirts3rdleg** [comment]
+1，坐等大佬

**Comment by playhappy1** [comment]
也是这个毛病
