### ISSUE TITLE
新的积分规则变了

### ISSUE THREAD

**Issue by wenrtxn** [studyhelperhelper/studyhelper#156]
最新新版积分规则表：
登录（每日上限1分）
每日答题（每日上限6分），
挑战答题（每日上限6分），
我要选读文章（每日上限12分）
视听学习（每日上限6分）
视听学习时长（每日上限6分）
分享（每日上限1分）
发表观点（每日上限1分）
本地频道（每日上限1分）
专项答题（每日上限10分）
每周答题（每日上限5分）
订阅（每日上限2分）
每日上限共计57分，但由于每周答题、专项答题、订阅，这三项并不是每天都有，所以每天固定的积分由原来的42分减少为40分。

**Comment by Wutong-bn** [comment]
帮顶！！今天刚变的，点辅助答题后面就自动跳回助手了，可能因为规则变了。跪求大佬更新(*σ´∀`)σ感恩感恩
