### ISSUE TITLE
运行速度

### ISSUE THREAD

**Issue by Wutong-bn** [studyhelperhelper/studyhelper#159]
有没人感觉运行有点慢的，，是不是我哪里没设置好，总感觉每个操作之间会顿几秒

**Comment by 85524365** [comment]
慢是为了照顾网速慢的朋友，太快容易报错

**Comment by Wutong-bn** [comment]
> 慢是为了照顾网速慢的朋友，太快容易报错

偶偶这样。。那得怎么停下来呀，得等它运行完吗（我运行了30分钟了有点慌hhhhhhh）

**Comment by 85524365** [comment]
这个版本确实不稳定，经常报错

**Comment by Wutong-bn** [comment]
hhh是的，我之前用的是一个叫猫咪助手的，它会有个弹窗可以控制，速度会快一点，只是前两天积分规则变了就运行不了了-。-

**Comment by Wutong-bn** [comment]
> 这个版本确实误差，经常报错

hhh是的，我之前用的是一个叫猫咪助手的，它会有个弹窗可以控制，速度会快一点，只是前两天积分规则变了就运行不了了-。-
