### ISSUE TITLE
运行后无法显示悬浮窗

### ISSUE THREAD

**Issue by Leo4ML** [studyhelperhelper/studyhelper#162]
手机：一加5t 
系统：安卓10&H2OS10
学习QG版本：2.15.1
学习助手版本：2.15.1-2
问题描述： 首次运行助手已给予修改存储权限，应用权限中已开启“应用显示在最上层”；运行助手后，可以正常执行脚本刷分，但唯独没有悬浮窗或其他任何助手正在运行的提示；
请问是取消了悬浮窗功能就是隐身刷分还是我这边设置错误有什么bug呢？

**Comment by zdbss** [comment]
作者好像一直就没有加悬浮窗的功能，反正我都是看屏幕，屏幕不亮了肯定就完成了。
