### ISSUE TITLE
分享获得积分方案是否考虑采用强国内分享

### ISSUE THREAD

**Issue by z9power** [studyhelperhelper/studyhelper#163]
分享获得积分方案是否考虑采用强国内分享，在没有装微信的前提下也可以独立运行。谢谢！

**Comment by 85524365** [comment]
装个微信也不麻烦。要是强国内分享，很容易被发现作弊

**Comment by z9power** [comment]
好的 谢谢大佬 我手动解决一下
其实是双开的问题 用miui双开的时候 从微信返回会跳双应用选择
