### ISSUE TITLE
大家新版学习正常吗

### ISSUE THREAD

**Issue by liuluo1979** [studyhelperhelper/studyhelper#164]
2.15.1-2版昨天只学了24分，重新运行也是停在首页不学。升级到2.15.1-3版后，还是学不了。

**Comment by HaDX-MLL** [comment]
还是看手机系统，我用的荣耀畅玩5X，刷的LineageOS 16，基本是原生安卓9，2.15.1-2版，这几天每天39分没问题（手机没装微信，就没点分享，差了1分）。

**Comment by liuluo1979** [comment]
我是小米10Pro MIUI12稳定版

**Comment by liuluo1979** [comment]
旧手机(HTC U11 安卓9.0)试过，也是不行😳
