### ISSUE TITLE
怀着感恩的心致大神

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#169]
大神，恳请  题库还和以前一样，放在不用root就能找到的目录下吧，这样修改起来也方便。

或者增加一个导入和导出题库的按钮，这样很方便，每次升级，自己都可以把旧题库导出来，就更完美了。

再次膜拜大神了！

**Comment by solife2020** [comment]
其实应该是这样建议：
题库增加管理功能，可以查找、修改或增加、删除。这样方便自己维护题库和管理题库
