### ISSUE TITLE
软件运行一会就自动停止

### ISSUE THREAD

**Issue by zsdw52** [studyhelperhelper/studyhelper#17]
华为手机，开启了无障碍，但是APP运行一会就会自动停止，新闻，评论，主页，视频这些界面都出现过。我是开启了APP后就没动手机了，也设置了常量，软件也没退出，但是检查发现无障碍已经被自动关闭，不知为何，请问知道如何解决？谢谢。

**Comment by studyhelperhelper** [comment]
后台锁一下APP试试，百度一下看看有没有手机自动关闭辅助服务的情况。

**Comment by zsdw52** [comment]
> 后台锁一下APP试试，百度一下看看有没有手机自动关闭辅助服务的情况。

已经锁了，还是一样的。
