### ISSUE TITLE
偶现观看视频的任务没有完成

### ISSUE THREAD

**Issue by grantting** [studyhelperhelper/studyhelper#170]

**Comment by 85524365** [comment]
今天我这边也出现只学习36分，看了一下，原来是学习文章的时候，把一个视频当成文章来学习了。
这样导致文章少学1篇，而且这个文章时长一直卡在视频上，导致时长也不够了。
建议大神：
1、文章多学1篇，学7篇。可以防止出现视频当成文章学习了。
2、每一篇文章都来随机数，时间1-2分钟。可以防止文章时长不够。
