### ISSUE TITLE
争上游的辅助第一题搜索太慢，希望作者修正下~

### ISSUE THREAD

**Issue by solife2020** [studyhelperhelper/studyhelper#173]
争上游的辅助第一题搜索出结果太慢，希望作者修正下~
另外题库中，关于 词语的有点少，希望增加。

**Comment by solife2020** [comment]
> 争上游的辅助第一题搜索出结果太慢，希望作者修正下~
> 另外题库中，关于 词语的有点少，希望增加。

**Comment by yooaiyim** [comment]
体库怎么用？ word 还是 txt 放哪啊 求指教

**Comment by zr325** [comment]
你在加载的时候就狂点搜索可以暂时解决第一题慢的问题，我觉得要想快，需要给出正确答案时连同选项一起给出，这样就不用从选项里挑了。

**Comment by solife2020** [comment]
这需要 作者加入进去。
