### ISSUE TITLE
感谢大神更新软件，期盼增加 导入和导出 题库按钮

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#175]
感谢大神更新软件，期盼 增加 一个 导入和导出题库按钮。
方便大家增加和修改题库。
再次感激大神。

**Comment by yooaiyim** [comment]
题库怎么用啊  保存为什么格式，放哪个位置，教我一下

**Comment by 85524365** [comment]
大神，怀念以前可以把题库保留出来的日子。
大神，期盼题库还是放在不用root就能读写的地方日。
