### ISSUE TITLE
小米9闪退

### ISSUE THREAD

**Issue by gethin520** [studyhelperhelper/studyhelper#18]
小米9 MIUI10  安卓9.0系统

**Comment by ling25938** [comment]
我红米K20 PRO 也是，新安装后就打不开了，要安装一个老版本在覆盖安装，可以打开。但是打开辅助学习无效果，自动退出学习强国，乱点屏幕。

**Comment by per2019** [comment]
你可以在设置下设置助手的权限：读写、访问网络等权限设置。
设置后就可以运行软件了。

**Comment by studyhelperhelper** [comment]
注意1.3.4版本对应的是  学习强国V2.6.0版本。
闪退请在安装过程中给助手存储权限。程序安装过程中需要将题库保存到本地。

**Comment by noway2014** [comment]
1.34版本，安装在8.1安卓下，能运行，但是卡在输入留言环节，在调出输入法输入留言中，没有反应。光标闪烁

**Comment by studyhelperhelper** [comment]
试试1.3.5

**Comment by noway2014** [comment]
解决了上面问题，但是存在无法自动运行挑战问题

**Comment by studyhelperhelper** [comment]
为了防止清理掉题库，我把题库放到根目录-包名文件夹下了，看看com. study. helper目录下有没有tiku. data。没有的话就会老是填错误答案。如果是什么答案也不选，可能又是辅助服务被关了，检查一下后台加锁的问题。我百度了一下确实有不少机型存在自动关闭辅助服务的情况，请自行搜索解决方案。
