### ISSUE TITLE
发表评论基本卡住

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#183]
大侠辛苦了，再次表示感激。

手机型号：华为p9
安卓：8.0
故障现象：
1、前天开始，基本上不能发表评论，自动退回到了studyhelper主界面。
或者发表评论后不能删除，卡在评论后的界面。
偶尔出现不停的发表评论，今天同一文章，竟然发表了6百多回复。
2、再次奢望一下，大侠能够把题库放到便于查看的地方，感激不尽啦！

**Comment by Mr-zhao98** [comment]
我下载不下来    你怎么下载的

**Comment by 85524365** [comment]
大神早就考虑到下载不方便了，直接软件升级就行。

1.强国版本2016.0--助手版本2.16-5，关闭发表评论，其他项目就能就能学习了。
 大神， 记得安卓8.0简单，比其他版本少1个back，以前版本估计有个判断语句，期盼大神加上。
2.强国版本2.17.0，助手2.17-3，也是卡在发表观点这一项目。
此外，卡在二人答题，总是反复问是否退出答题。

推测还是安卓8比较简单，高版本的安卓11等需要多一个back，到安卓8这里，少1个back即可，大神，还是建议增加一个判断语句。

感恩感激膜拜

**Comment by 85524365** [comment]
2.17-3版本，尽管卡在   “确定要退出房间”  界面，但实际上  “双人对战”  已经做完了，而且胜率很高，感激大神。
但是四人答题，第一题答题太慢，基本上胜者答完第三2题，我们才开始


瑕不掩瑜，仍然支持感恩大神
