### ISSUE TITLE
4人答题第一题搜索慢，是安卓版本的原因

### ISSUE THREAD

**Issue by xg805652411** [studyhelperhelper/studyhelper#190]
我用几个不同安卓版本手机测试了一下4人对战，安卓10可以正常快速答第一题，10以下的版本会出现第一题迟迟不出答案的情况。

**Comment by s-mason** [comment]
双人对战总是无法退出。Android 11，强国是2.17。

**Comment by nysamurai** [comment]
安卓10以上，第一题也有延迟答题。
