### ISSUE TITLE
期盼下个版本能解决，安卓8.0 ，不能发表观点，以及二人答题不能退出的2个bug

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#192]
大神，感恩中。估计咱也快升级了。

期盼下个版本能解决，安卓8.0 ，不能发表观点，以及二人答题不能退出的2个bug

**Comment by 20057842** [comment]
我的也是安卓8，通常手动完成这几项，用输入法的剪切板功能，固定词语，一分钟内解决两台手机的留言1+分享2+本地频道1。其余多谢大神的心血结晶。
