### ISSUE TITLE
每日答题重复答题

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#195]
大神，咱的软件可以跨版本用，牛啊！感谢膜拜大佬
使用中新发现：每日答题重复做题

只要运行软件，无论每日答题是否已经满分，都要重复再做一遍。

个人猜测是不是每日答题分数现在低了，建议<5运行，=5就不要运行了。
再次感谢

**Comment by solife2020** [comment]
好久都没有更新了。
