### ISSUE TITLE
现在最新18，希望作者优化争上游的第一题搜题速度，感谢！！！

### ISSUE THREAD

**Issue by grantting** [studyhelperhelper/studyhelper#199]

**Comment by DoAcha** [comment]
我的争上游自动答题第一题速度也是很慢！
且“助手2.17.0-3”的功能“答题争上游”在“争上游答题”的时候搜第一题的时候也非常慢，点“搜索”后出题速度大约和自动答题第一题的速度一样慢！
手机：小米5X
MIUI版本：MIUI 11.0.3稳定版（11.0.3.0-ODBCNXM）
安卓版本：安卓8.1.0
