### ISSUE TITLE
视听时长可以听广播呀！能和看文章、答题同时进行，都有分数，不算利用bug

### ISSUE THREAD

**Issue by wejblll** [studyhelperhelper/studyhelper#20]
你好，右下角电台\听新闻广播\随便点一个电台，然后可以去看文章、答题，这几项分数都满了之后再刷6个百灵就好了，听广播的分数有一些延时，只要点一下广播的悬浮图标，在点一下电台名称它会最大会，再返回就能获得分数了！~

**Comment by noway2014** [comment]
如何最快获得电台分数？

**Comment by studyhelperhelper** [comment]
要大规模调整代码啊，脑细胞暂时不够。
