### ISSUE TITLE
大神，挑战答题的建议

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#200]
大神，挑战答题刷题库平均1分钟10个，1道题平均6秒。
目前题库大约1800多个，即使刷题全对，刷1次也需要3个多小时。
大神，下个版本，能否缩短一下答题时间，1分钟做15-25题也是不错的。🙏拜托啦，当然如果麻烦，请无视

**Comment by xiaoguich** [comment]
你要刷这么多干嘛？能拿满分还不够？

**Comment by xiaoguich** [comment]
> 大神，挑战答题刷题库平均1分钟10个，1道题平均6秒。
> 目前题库大约1800多个，即使刷题全对，刷1次也需要3个多小时。
> 大神，下个版本，能否缩短一下答题时间，1分钟做15-25题也是不错的。🙏拜托啦，当然如果麻烦，请无视

你要刷这么多干嘛？能拿满分还不够？

**Comment by 85524365** [comment]
不告诉你

**Comment by 85524365** [comment]
> > 大神，挑战答题刷题库平均1分钟10个，1道题平均6秒。
> > 目前题库大约1800多个，即使刷题全对，刷1次也需要3个多小时。
> > 大神，下个版本，能否缩短一下答题时间，1分钟做15-25题也是不错的。🙏拜托啦，当然如果麻烦，请无视
> 
> 你要刷这么多干嘛？能拿满分还不够？

不告诉你
