### ISSUE TITLE
能不能适配下模拟器？

### ISSUE THREAD

**Issue by Funesoul** [studyhelperhelper/studyhelper#201]
虽说是有点挑剔但还是感觉效率不高损耗了电池

**Comment by 20057842** [comment]
充分利用旧手机啊（安卓8以上）。我放了两台手机在单位（华为P8+努比亚Z9）

**Comment by 85524365** [comment]
p8也是安卓区8吗？

**Comment by 20057842** [comment]
记错了，华为的更新到最高只能到安卓6，我通过root，解锁刷了CM14第三方ROM，相机不能用，但是能挂机。
LineageOS 14.1 gra_l09, ROM for the Huawei P8。ROM OS Version: 7.x Nougat
ROM Kernel: Linux 3.10.x
Based On: LineageOS
