### ISSUE TITLE
希望作者平安

### ISSUE THREAD

**Issue by neveruknow** [studyhelperhelper/studyhelper#203]
😥

**Comment by xiaoguich** [comment]
这是另类催更吗 逗乐我了

**Comment by xindian720** [comment]
楼主啥意思了？

**Comment by lukesijia** [comment]
> 这是另类催更吗 逗乐我了

很早以前看到过有新闻的，说制作这种，被。。。带走了

**Comment by lukesijia** [comment]
> 楼主啥意思了？

作者好久没更新了，有点担心

**Comment by 85524365** [comment]
不要危言耸听，那个被带走人开发的的是注册收费版，职业公务员，最最关键的是他的软件有木马，在52破解上给人破解后，就自动格式化使用破解版本用户的电脑DEF盘等，得罪了很多不该得罪的人，被人报案，是被控损坏别人计算机数据，被刑事拘留的，跟这个完全两码事。

**Comment by neveruknow** [comment]
> 不要危言耸听，那个被带走人开发的的是注册收费版，职业公务员，最最关键的是他的软件有木马，在52破解上给人破解后，就自动格式化使用破解版本用户的电脑DEF盘等，得罪了很多不该得罪的人，被人报案，是被控损坏别人计算机数据，被刑事拘留的，跟这个完全两码事。

哦哦，这样的啊，我感觉最近风声越来越紧，担心环境越来越严😨，没事就好，希望只是作者忙。。。
