### ISSUE TITLE
小米MIX2 安卓8.0.0 MIUI10.3 打开1.3.4版本助手闪退

### ISSUE THREAD

**Issue by LIUYUYANSZ** [studyhelperhelper/studyhelper#21]
小米MIX2 安卓8.0.0 MIUI10.3 打开1.3.4版本助手闪退

**Comment by LIUYUYANSZ** [comment]
1.3.3版本打开正常

**Comment by per2019** [comment]
设置软件的权限

**Comment by per2019** [comment]
我的运行不了每日答题，不会填写答案，请高手教一下。手机系小米的mix2s

**Comment by LIUYUYANSZ** [comment]
设置权限也没有用打开软件就闪退

**Comment by studyhelperhelper** [comment]
1.3.4数据库写入到存储器，可以查看到，卸载重装试试吧。

**Comment by studyhelperhelper** [comment]
每日答题和发表评论一个问题，至今未找到原因，估计是关于粘贴文本的问题，我的华为手机正常。

**Comment by LIUYUYANSZ** [comment]
@studyhelperhelper 发现问题了需要手动设置助手的读写手机存储

**Comment by 85524365** [comment]
华为p9  1.33能运行，但1.34闪退

**Comment by ohhhyy** [comment]
> @studyhelperhelper 发现问题了需要手动设置助手的读写手机存储

可以用了，感谢

**Comment by ohhhyy** [comment]
是不是助手只适配最新版？
我觉得就适配某些大更新的版本就好
