### ISSUE TITLE
2.20.0-1新版本，开始收费了！

### ISSUE THREAD

**Issue by LvDeShei** [studyhelperhelper/studyhelper#210]
2.20.0-1新版本，开始收费了！

**Comment by szsyzx** [comment]
你听谁说的,你是作者代言人?

**Comment by DoAcha** [comment]
难道没收费？怎么打开2.20.0-1的时候提示我输入激活码呢？

**Comment by DoAcha** [comment]
卸载掉2.19*版本后，再安装2.20.0-1新版本，的却出现了需要激活码的情况！
刚才又测试了一下直接在2.19*版本的基础上点击“设置”中的“检查最新版本”来升级，升级后就不会出现需要激活码的情况了，不知道怎么回事！

**Comment by studyhelperhelper** [comment]
无收费计划，只有这个渠道下载是原版。
