### ISSUE TITLE
题库怎么自己更新 我有个很全的题库  你这个题库太少了

### ISSUE THREAD

**Issue by sd252457109** [studyhelperhelper/studyhelper#216]
题库怎么自己更新 我有个很全的题库  你这个题库太少了

**Comment by xiaoguich** [comment]
> 题库怎么自己更新 我有个很全的题库 你这个题库太少了

你可以把题库共享给作者

**Comment by ygflycn** [comment]
争上游不会超过2000道题吧，包括每日答题的大而全的题库不会影响答题速度吗？

**Comment by f2m4f2m4** [comment]
> 争上游不会超过2000道题吧，包括每日答题的大而全的题库不会影响答题速度吗？

大佬现在争上游题库已经2400多道题了。

**Comment by s1n1209** [comment]
题库可以共享一下吗
