### ISSUE TITLE
小米安卓10 争上游失效

### ISSUE THREAD

**Issue by zqguang3708** [studyhelperhelper/studyhelper#219]
有时候是未真正打开辅助服务，后台杀死程序后，try again。

**Comment by zqguang3708** [comment]
开启了辅助服务，打开争上游的悬浮窗，在争上游答题时，点击放大镜并没有任何反应。有人遇到过类似的问题吗？

**Comment by DoAcha** [comment]
每次使用，先关闭“辅助服务”，然后再打开“辅助服务”，就解决问题了！
