### ISSUE TITLE
填空题可以呼出输入窗口但是没有填写内容，已经给了助手存储权限

### ISSUE THREAD

**Issue by LIUYUYANSZ** [studyhelperhelper/studyhelper#23]
填空题可以呼出输入窗口但是没有填写内容，已经给了助手存储权限

助手版本1.3.4 学习版本2.6.0 百度输入法

**Comment by studyhelperhelper** [comment]
应该是答案未粘贴成功，我再研究一下。我自己的手机是华为，输入法是百度输入法华为版就没问题，这种情况就屏蔽掉，过后手动完成每日答题吧。发表评论能成功吗？

**Comment by LIUYUYANSZ** [comment]
@studyhelperhelper 我测试下评论先

**Comment by LIUYUYANSZ** [comment]
@studyhelperhelper 试下了无法发表评论

**Comment by studyhelperhelper** [comment]
那应该是一个问题，再更新时调整一下试试。

**Comment by studyhelperhelper** [comment]
已上传了1.3.5版本，请试用一下。

**Comment by per2019** [comment]
还是不行，感觉手机系统输入法适配问题吧！
请高人帮忙解诀！小米手机

**Comment by per2019** [comment]
升到最新的软件可以发表评论了。但是每日答题的自动填的答案全部不正确的。

**Comment by per2019** [comment]
如何复制试题库入手机内？请指教！

**Comment by studyhelperhelper** [comment]
重装一下，安装过程中给APP存储权限。

**Comment by noway2014** [comment]
1.3.5-2.6.0版本，已经解决每日答题，正常。但是运行到挑战…时候，无法开始挑战。就是其他项目都完成了，挑战一直不开始…停在阅读那里好久好久。
