### ISSUE TITLE
1.3.5版本测试反馈

### ISSUE THREAD

**Issue by LIUYUYANSZ** [studyhelperhelper/studyhelper#24]
测试了以下几个功能

每日答题 正常
评       论 可以正常发布评论并成功删除，但是删除完评论后没有后续操作

其他功能还在测试

**Comment by per2019** [comment]
小米手机每日答题，评论，都正常！！！无存上以上情况！

**Comment by noway2014** [comment]
今天两台安装测试，发现浏览的内容基本一样的。这样很危险吧。能否加些参数，不同使用者，浏览的文章可以分开或者时长不要一样

**Comment by studyhelperhelper** [comment]
时长一定范围内已经做了随机。内容不同时段浏览应该不会雷同，后期再考虑一下。

**Comment by jackywang615** [comment]
米6相同问题

**Comment by noway2014** [comment]
1.36问题，运行过程多次自行停止，自动黑屏（屏幕没设置常亮，但是以前版本1.35/34都会在运行过程保持长亮）。看着运挑战，但是完全0分。感觉1.36不行。不如1.35

**Comment by wenyanxing** [comment]
评论删除后 不动了。
