### ISSUE TITLE
大佬能不能出个苹果手机用的版本？

### ISSUE THREAD

**Issue by HarryDean2010** [studyhelperhelper/studyhelper#240]
RT，平时用的是苹果手机，而且相信苹果手机用户也有不少人想用这个软件。感谢您制作这么优秀的软件！

**Comment by waterun** [comment]
苹果除非越狱

**Comment by wuwu955** [comment]
> RT，平时用的是苹果手机，而且相信苹果手机用户也有不少人想用这个软件。感谢您制作这么优秀的软件！

+1
