### ISSUE TITLE
是不是最新版本没有题库？

### ISSUE THREAD

**Issue by wellanren** [studyhelperhelper/studyhelper#244]
是不是最新版本没有题库？我昨天更新了最新版本，重装了3次，答题时搜索题，都显示没有。

**Comment by ksong008** [comment]
最新版有问题，应该是题库问题，导致答题永远只选a

**Comment by studyhelperhelper** [comment]
安装前先卸载旧版本，再安装。

**Comment by ksong008** [comment]
> 安装前先卸载旧版本，再安装。

重装了几次，还是一样

**Comment by studyhelperhelper** [comment]
等会更新下一版本吧。

**Comment by ksong008** [comment]
> 等会更新下一版本吧。

辛苦了

**Comment by ksong008** [comment]
> 等会更新下一版本吧。

新版应该可以了，题库可以出来了，感谢

**Comment by anketong** [comment]
> 

哥哥，你在我心中就是神，真的，挖心龙门阵，你一定不要忘记这个APP，及时更新，求求你了，我都要被逼疯了。求求你了哥老关~
