### ISSUE TITLE
四人对战&双人对战问题

### ISSUE THREAD

**Issue by ksong008** [studyhelperhelper/studyhelper#245]
最新版本，四人对战&双人对战一直随机卡死，是设置中点击延迟参数问题吗？

**Comment by studyhelperhelper** [comment]
网络不好，点击的太快，将设置中点击速度延时调更长时间。

**Comment by ksong008** [comment]
> 网络不好，点击的太快，将设置中点击速度延时调更长时间。

嗯，网络应该没问题，觉得是服务器反应慢，我调下 延迟试试。
