### ISSUE TITLE
为啥不在设置那里加上“每周答题”和“专项答题”开关

### ISSUE THREAD

**Issue by ogwogw** [studyhelperhelper/studyhelper#247]
为啥不在设置那里加上“每周答题”和“专项答题”开关

**Comment by yooaiyim** [comment]
收声吧你，这么一点自己手动能死？

**Comment by UnaAtadura-Eris** [comment]
> 为啥不在设置那里加上“每周答题”和“专项答题”开关

找找别的项目的源码，其实是有写了这两个项目的函数的，只不过没有调用，自己改改就好了
