### ISSUE TITLE
4/3更新后问题

### ISSUE THREAD

**Issue by jingyudong1113** [studyhelperhelper/studyhelper#249]
答题延时设置500，四人答题时还是一直从强国软件跳转到助手，然后来回跳

**Comment by didiheqiqi** [comment]
好像偶尔会卡住

**Comment by conanlm** [comment]
不知道是不是我延时设置太低了，到第二题就卡住了，调高后就好了
没做太多测试，不确定是不是延时多问题

**Comment by didiheqiqi** [comment]
能加你的企鹅交流一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月4日(星期天) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [studyhelperhelper/studyhelper] 4/3更新后问题 (#249)





 
不知道是不是我延时设置太低了，到第二题就卡住了，调高后就好了
 没做太多测试，不确定是不是延时多问题
