### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by lls1043** [studyhelperhelper/studyhelper#25]
荣耀八闪退。Xplay6不能安装。

**Comment by aoyoo111** [comment]
打开存储权限就不会闪退了

**Comment by rhww** [comment]
1.3.6也闪退啊，小米8

**Comment by kentmay** [comment]
> 打开存储权限就不会闪退了

仍然闪退，不知道是否跟学习强国app升级有关

**Comment by aoyoo111** [comment]
> > 打开存储权限就不会闪退了
> 
> 仍然闪退，不知道是否跟学习强国app升级有关

我这里一切正常啊

**Comment by kentmay** [comment]
抱歉，闪退是因为我自己的原因，xxqg版本未更新到最新版
