### ISSUE TITLE
清除数据

### ISSUE THREAD

**Issue by pokerloz** [studyhelperhelper/studyhelper#252]
要想每天稳定运行最好每天都将软件的数据和缓存清空。希望大佬下次更新能优化一下

**Comment by P-boss** [comment]
将题库数据库设置大一点就不会在插入数据的时候报错了

**Comment by P-boss** [comment]
可以下载我的题库去替换即可正常使用

**Comment by pokerloz** [comment]
> 可以下载我的题库去替换即可正常使用

感谢

**Comment by lijunzi** [comment]
> 可以下载我的题库去替换即可正常使用
在哪下载？

**Comment by lijunzi** [comment]
> 可以下载我的题库去替换即可正常使用

在哪下载呢？

**Comment by chowyuanchen** [comment]
怎么替换题库啊？
