### ISSUE TITLE
求求更新

### ISSUE THREAD

**Issue by 1201net** [studyhelperhelper/studyhelper#276]
这个算是最好用的答题助手了，一直使用到近期，但最近四人和双人答题开始抽风，不听使唤了，求大神更新！你知道，千万人都在心里默默的感谢着你！FUCK学习强国！

**Comment by xltonglx** [comment]
同求

**Comment by studyhelperhelper** [comment]
请关闭双人和四人对战吧，用不了了，关闭这两个可以得39分，手动答题吧。解决不了，双人和四人不支持辅助服务了。

**Comment by xltonglx** [comment]
> 请关闭双人和四人对战吧，用不了了，关闭这两个可以得39分，手动答题吧。解决不了，双人和四人不支持辅助服务了。

大佬来啦

**Comment by Suwipe** [comment]
hamibot里有用华为云OCR实现的，但是答题速度比这个工具以前的速度满了不是一点，现在就是把这个工具关了双人四人在用，hamibot里的只用双人四人答题

**Comment by 1201net** [comment]
> hamibot里只有把这个工具关了双人四人在用，hamibot里只有双人四人答题

能说详细一点吗？多谢！

**Comment by TanningR** [comment]
> > hamibot里只有把这个工具关了双人四人在用，hamibot里只有双人四人答题
> 
> 能说详细一点吗？多谢！

https://hamibot.com/marketplace/aQlXd

**Comment by 1201net** [comment]
> > > hamibot里只有把这个工具关了双人四人在用，hamibot里只有双人四人答题
> > 
> > 
> > 能说详细一点吗？多谢！
> 
> https://hamibot.com/marketplace/aQlXd

非常感谢，学习了！

**Comment by lijunzi** [comment]
好像挑战答题也不行了。。

**Comment by GaviTate** [comment]
> 请关闭双人和四人对战吧，用不了了，关闭这两个可以得39分，手动答题吧。解决不了，双人和四人不支持辅助服务了。
👍
给你发了邮件，看看能不能用吧
