### ISSUE TITLE
关于题库提取及分享

### ISSUE THREAD

**Issue by YK202** [studyhelperhelper/studyhelper#277]
您好，一直用你开发的助手。
关于四人赛双人赛的题库。
有办法提取吗？谢谢

**Comment by alikankan** [comment]
你电脑安装到模拟器上就可以提取题库

**Comment by athunder2020** [comment]
> 您好，一直用你开发的助手。 关于四人赛双人赛的题库。 有办法提取吗？谢谢

我有题库，最新的，但是我想知道您怎么刷四人的。

**Comment by losolowar** [comment]
> 你电脑安装到模拟器上就可以提取题库

有什么步骤吗？  谢谢
