### ISSUE TITLE
我双人 和 四人 感觉慢呢

### ISSUE THREAD

**Issue by wangshihai** [studyhelperhelper/studyhelper#283]
我双人 和 四人 感觉慢呢

**Comment by studyhelperhelper** [comment]
这OCR速度已经很快了，这要感谢百度开源的飞桨OCR，百度牛逼。原来用的自己训练的OCR那速度才感人呢，根本没法用。本来已经放弃了，正是看到了百度的飞桨，才更新的。

**Comment by GarfieldR** [comment]
> 这OCR速度已经很快了，这要感谢百度开源的飞桨OCR，百度牛逼。原来用的自己训练的OCR那速度才感人呢，根本没法用。本来已经放弃了，正是看到了百度的飞桨，才更新的。

大爷辛苦啦

**Comment by GarfieldR** [comment]
试了下在鸿蒙机上比安卓机要快一些

**Comment by xltonglx** [comment]
> 这OCR速度已经快了，这要感谢百度开源的飞桨OCR，百度牛逼。原来用自己的训练的OCR速度才感人呢，本来已经不能用了。的飞桨，才更新的。

谢谢大佬

**Comment by yooaiyim** [comment]
> 这OCR速度已经很快了，这要感谢百度开源的飞桨OCR，百度牛逼。原来用的自己训练的OCR那速度才感人呢，根本没法用。本来已经放弃了，正是看到了百度的飞桨，才更新的。

感谢你  真的好用

**Comment by ywq123haoben** [comment]
> 这OCR速度已经很快了，这要感谢百度开源的飞桨OCR，百度牛逼。原来用的自己训练的OCR那速度才感人呢，根本没法用。本来已经放弃了，正是看到了百度的飞桨，才更新的。

谢谢大佬

**Comment by JumperMan** [comment]
> 这OCR速度已经很快了，这要感谢百度开源的飞桨OCR，百度牛逼。原来用的自己训练的OCR那速度才感人呢，根本没法用。本来已经放弃了，正是看到了百度的飞桨，才更新的。

谢谢dalao!!

**Comment by 85524365** [comment]
> 

感激大神
