### ISSUE TITLE
对战的时候不答题

### ISSUE THREAD

**Issue by hazardeden10** [studyhelperhelper/studyhelper#285]
您好，机型华为mate20pro，四人对战的时候不答题，最后得0分，这个版本答题好像有点问题

**Comment by hazardeden10** [comment]
而且经常会跳回主界面

**Comment by han-pf** [comment]
确实有点问题

**Comment by fjyl001** [comment]
小米系统也是这样，呆着不动，别人都满分了，还是不动，近期都是0分，希望能更新到2.23.0版本的处理方式
