### ISSUE TITLE
你好，刷一次只有26分，而且四人赛满分不退出，一直匹配

### ISSUE THREAD

**Issue by wordpython** [studyhelperhelper/studyhelper#287]
感谢作者的助手，以下是我使用过程中发现的问题，麻烦作者修复：
1.启动助手刷学习强国时，“有效阅读和播放文章”模块只拿了5分，“有效播放视频”模块也只拿了6分，从启动助手到结束（长达10分钟没有任何刷分动作）历时32分钟刷到的分数只有26分
2.自动四人比赛两局满分后没有退出，一直在匹配四人比赛。

**Comment by XspYedan** [comment]
一直在匹配四人比赛，这个确实我也是这样
