### ISSUE TITLE
开始学习按钮不见了

### ISSUE THREAD

**Issue by datouvb** [studyhelperhelper/studyhelper#291]
第一次使用后，打开FZ服务下面的开始FZ学习按钮不见了

**Comment by studyhelperhelper** [comment]
请关闭辅助服务再次打开，可以解决问题。

有的机型经常打开辅助服务失败，正常打开辅助服务后，按钮就变成了开始辅助学习。如果未变，打开辅助服务对话框不会消失，说明打开辅助服务未成功。请关闭辅助服务再次打开。

**Comment by datouvb** [comment]
> 请关闭辅助服务再次打开，可以解决问题。
> 
> 有的机型经常打开辅助服务失败，正常打开辅助服务后，按钮就变成了开始辅助学习。如果未变，打开辅助服务对话框不会消失，说明打开辅助服务未成功。请关闭辅助服务再次打开。

果然，可以了，棒棒哒！！！
