### ISSUE TITLE
大侠，请问这是针对哪个版本的？

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#3]
我目前学习强国的版本是2.4的，发现不能使用。
大侠，请问这是针对哪个版本的？

**Comment by studyhelperhelper** [comment]
最新版本的。发现个bug，程序开始的时候要去查询已经学习了多少分，容易卡在点击“我的”选项卡后，找不到“学习积分”按钮，造成卡在这个界面，一直循环寻找还是找不到。马上更新个新版本。
