### ISSUE TITLE
1.3.6问题汇总

### ISSUE THREAD

**Issue by fatpot** [studyhelperhelper/studyhelper#30]
我用的oppo手机。
1.评论删除后没有动作。
2.阅读文章长时间后没有动作。
3.无法分享。
4.订阅可以点击然后在取消就好了
5.收藏可以一直收藏

1.2问题有时好有时坏。
另外还有一个，辅助服务自动关闭，每次都是要重新打开

**Comment by fatpot** [comment]
视频都是播放新闻联播

**Comment by iyoujian** [comment]
答题最近老是出错，是不是题库的问题？

**Comment by kentmay** [comment]
程序有时会随机停止，屏幕熄灭或者停止动作。
其他没有发现问题，在运行时答题，收藏，评论，看文章，视频都没问题。
1.3.6 Samsung S7E android8.0 讯飞输入法
