### ISSUE TITLE
双人对战中途弹出退出窗口

### ISSUE THREAD

**Issue by GarfieldR** [studyhelperhelper/studyhelper#302]
最近几天双人赛老是中途弹出退出窗口，不知大家有没有遇到。

**Comment by nihaolixin** [comment]
没有遇到过，我一起正常使用，每天稳定46




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 上午9:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[studyhelperhelper/studyhelper] 双人对战中途弹出退出窗口 (Issue #302)





 
最近几天双人赛老是中途弹出退出窗口，不知大家有没有遇到。

**Comment by 2592199042** [comment]
> 没有遇到过，我一起正常使用，每天稳定46
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "studyhelperhelper/studyhelper" ***@***.***&gt;; 发送时间:&nbsp;2022年2月9日(星期三) 上午9:05 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[studyhelperhelper/studyhelper] 双人对战中途弹出退出窗口 (Issue #302) 最近几天双人赛老是中途弹出退出窗口，不知大家有没有遇到。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

你好，下载链接的打不开怎么办

**Comment by studyhelperhelper** [comment]
https://raw.githubusercontent.com/studyhelperhelper/studyhelper/master/learningsudoku1.2.36.0-2.rar
