### ISSUE TITLE
发现了一个新软件，稳定多人

### ISSUE THREAD

**Issue by hujinchaopk** [studyhelperhelper/studyhelper#304]
我用蓝奏浏览器分享了[自动学习_v1.4], 下载链接:https://wwr.lanzoui.com/iDT7T0087zij  提取码 : d78c, 你可以不限速下载哦

**Comment by nihaolixin** [comment]
你礼貌吗？拿着别人的东西分享，还要卡密的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月19日(星期六) 凌晨3:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[studyhelperhelper/studyhelper] 发现了一个新软件，稳定多人 (Issue #304)





 
我用蓝奏浏览器分享了[自动学习_v1.4], 下载链接:https://wwr.lanzoui.com/iDT7T0087zij  提取码 : d78c, 你可以不限速下载哦
