### ISSUE TITLE
最近发现一个新的辅助，希望对你有帮助

### ISSUE THREAD

**Issue by w1440907679** [studyhelperhelper/studyhelper#305]
https://wwa.lanzoub.com/ihmj800rwvub

**Comment by Littlekunlun** [comment]
太好用了，已经用了，终于有能用的了！！就是请问下这个软件有没有群之类的，想加进去，及时过去更新！！

**Comment by LINALONG1993** [comment]
很棒！有没有群呀！

**Comment by nihaolixin** [comment]
这个有群吗？有备无患。

**Comment by hujinchaopk** [comment]
[> 

https://t.me/+4iWz2PdvNJ81ZTZl](https://t.me/+4iWz2PdvNJ81ZTZl)
电报群
