### ISSUE TITLE
小米手机显示无法运行

### ISSUE THREAD

**Issue by etgyd** [studyhelperhelper/studyhelper#306]
miui 12.5.8 显示无法运行

**Comment by GarfieldR** [comment]
我的miui 12.5.10正常

**Comment by hujinchaopk** [comment]
试试新版本更新了我用蓝奏浏览器分享了[自动学习_v1.72], 下载链接:https://wwp.lanzoup.com/iYEXS010lwje  提取码 : akuf, 你可以不限速下载哦

**Comment by lgq215** [comment]
> miui 12.5.8 显示无法运行

清掉助手和强国的后台，在无障碍里面关闭助手，重启手机，先打开助手，通过助手开启无障碍里面的开关，然后再点助手里面的答题。

**Comment by studyhelperhelper** [comment]
没有小米手机测试

**Comment by qikenao** [comment]
如有重要的事，请回复，
请直接打电话！
不论是什么
