### ISSUE TITLE
能否自动题库更新

### ISSUE THREAD

**Issue by lls1043** [studyhelperhelper/studyhelper#310]
最近四人、双人赛，错题太多了，老大能否设计自动更新题库？

**Comment by lls1043** [comment]
据说不是题库的问题，是可选项位置的问题。

**Comment by GarfieldR** [comment]
和题库没关系，学习强国把选项打乱了

**Comment by GaviTate** [comment]
可能需要把选项的内容识别加进去，题库里也得把答案内容加上。算法更复杂了，要更新的话估计得花点时间，耐心等等吧。白P的分数，少就少点呗
