### ISSUE TITLE
新版本中的四人赛 ，两次比赛结束后没有退出，一直进行四人赛答题

### ISSUE THREAD

**Issue by wordpython** [studyhelperhelper/studyhelper#315]
麻烦优化以下

**Comment by GaviTate** [comment]
这个是正常设定，issues可以关了

> 麻烦优化以下

**Comment by lidazhaoha** [comment]
我也是一直在进行4人赛

**Comment by ygfly** [comment]
作者就是这样设计的。不过也觉得这个设计意义不大，多答那么几局意义不大，另外，求胜不易但求败的话完全有很多办法做到。反正我是两局答完直接强行退出，然后重新启动助手，答完其他的，还能节省点时间。
