### ISSUE TITLE
1.2.35版的建议

### ISSUE THREAD

**Issue by GaviTate** [studyhelperhelper/studyhelper#316]
试了试1.2.35.0-1，QG版本也升级到对应的.35版，设置不同的参数都答了几次。准确率很高，美中不足就是稍微慢了点。
目前肉测是文字内容多的（包括题干本身短但是”来源“的文字多），用时明显会长一些。

考虑优化识别或者检索的效率：
- 排除”来源“内容
- 题干截取一定字数
- 选项截取一定字数

**Comment by studyhelperhelper** [comment]
最终是识别速度问题。
