### ISSUE TITLE
更新2.35后开启辅助进入XXQG主页就没反应了

### ISSUE THREAD

**Issue by Soxyoung** [studyhelperhelper/studyhelper#318]
2.33开始用的(2.33辅助xxqg每天40+)，
手机为小米4C,系统android7(miui10.1) 内存3+32，安装shudu2.35，xxqg为2.35（后来升级为2.36），
表现为开启辅助自动运行XXQG后进入主页没有后续了（多次尝试卸载安装重启，等好几分钟一直在主页没反应），
卸载shudu后重装2.33可以辅助学习（xxqg2.36版本， 旧的2.33助手也可以辅助得分）。

**Comment by Soxyoung** [comment]
提交时网络卡顿，忽略

**Comment by laoqiuqiu** [comment]
xxqg退到2.35吧，作者不会跟着更新那么快。我感觉除非作者自己有需求了才会更新。

**Comment by Soxyoung** [comment]
> xxqg退到2.35吧，作者不会跟着更新那么快。我感觉除非作者自己有需求了才会更新。

作者回复了，说是无障碍有时候开启失败。xxqg和助手都回退到2.33了
