### ISSUE TITLE
更新shudu2.35后开启辅助进入XXQG主页就没反应了

### ISSUE THREAD

**Issue by Soxyoung** [studyhelperhelper/studyhelper#319]
2.33开始用的(2.33辅助xxqg每天40+)体验很不错，
手机为小米4C,系统android7(miui10.1) 内存3+32，安装shudu2.35，xxqg为2.35（后来升级为2.36），
悬浮权限和无障碍权限也开启了。
表现为开启辅助自动运行XXQG后进入主页没有后续了（多次尝试卸载安装重启，等好几分钟一直在主页没反应），
卸载shudu后重装2.33可以辅助学习（xxqg2.36版本， 旧的2.33助手也可以辅助得分）。

**Comment by luyan29** [comment]
同样的问题，权限都给了，进入APP首页后也没有出现悬浮窗，无任何反应

**Comment by wenrtxn** [comment]
使用没问题，开始也出现这个问题，最后重新给了无障碍权限才可以了

**Comment by studyhelperhelper** [comment]
这个问题没解决，有的手机辅助服务打开后没反应，需要再次关闭，再次开启才行。只有"打开辅助服务"这个按钮消失了，才说明辅助服务已正常开始。手机屏幕上会弹出短暂提示，辅助服务已连接。
业余开发作者，漏洞较多，凑合用吧。

**Comment by Soxyoung** [comment]
> 这个问题没解决，有的手机辅助服务打开后没反应，需要再次关闭，再次开启才行。只有"打开辅助服务"这个按钮消失了，才说明辅助服务已正常开始。手机屏幕上会弹出短暂提示，辅助服务已连接。 业余开发作者，漏洞较多，凑合用吧。

太客气了，有的用就不错了，再怎么样也比回归石器时代来的好哈哈。我是在无障碍里面给shudu权限后（"打开辅助服务"这个按钮消失了），手机屏幕上会弹出短暂提示“数独学习已连接XXQG”后，点击开始辅助学习进去XXQG没反应。回退到2.33了，不要对战的分数，也很满意。

**Comment by Soxyoung** [comment]
> 使用没问题，开始也出现这个问题，最后重新给了无障碍权限才可以了

请问“重新给了无障碍权限”具体是怎么操作的，能介绍下吗。我是xxqg和助手都关掉后用小米自带清理内存的工具清理内存。然后重新进入助手，在无障碍赋权后开始辅助，还是没反应。

**Comment by Soxyoung** [comment]
> 同样的问题，权限都给了，进入APP首页后也没有出现悬浮窗，无任何反应

我回退2.33了，双人、四人的分不要了。

**Comment by luyan29** [comment]
> > 同样的问题，权限都给了，进入APP首页后也没有出现悬浮窗，无任何反应
> 
> 我回退2.33了，双人、四人的分不要了。其他的还是很稳。

请问在哪下2.33安装包

**Comment by Soxyoung** [comment]
> > > 同样的问题，权限都给了，进入APP首页后也没有出现悬浮窗，无任何反应
> > 
> > 
> > 我回退2.33了，双人、四人的分不要了。其他的还是很稳。
> 
> 请问在哪下2.33安装包

豌豆荚等

**Comment by studyhelperhelper** [comment]
已更新到2.36.0
