### ISSUE TITLE
似乎有一个bug

### ISSUE THREAD

**Issue by noway2014** [studyhelperhelper/studyhelper#32]
看视频时候，如果节省流量，强国可以在播放界面提示用xxxm流量时候，不点击播放，这个界面停留着，等xx分钟，也算看了。
现在是，如果用助手，强国视频这种情况下不开流量播放出画面，助手就过不去。能否修正？！

**Comment by rhww** [comment]
> 看视频时候，如果节省流量，强国可以在播放界面提示用xxxm流量时候，不点击播放，这个界面停留着，等xx分钟，也算看了。
> 现在是，如果用助手，强国视频这种情况下不开流量播放出画面，助手就过不去。能否修正？！

在qg设置里打开在移动流量下自动打开视频即可。

**Comment by noway2014** [comment]
楼上的，问题是，就是想省流量不想打开嘛
