### ISSUE TITLE
双人和四人赛容易卡住，能解决吗?

### ISSUE THREAD

**Issue by lxxy584604730** [studyhelperhelper/studyhelper#321]
一旦卡主，只能眼睁睁看着别人答题，自己不能操作，能不能破解这个问题?

**Comment by studyhelperhelper** [comment]
设置里面点击速度延时，设定大一点，300毫秒肯定不卡。

**Comment by lxxy584604730** [comment]
> 设置里面点击速度延时，设定大一点，300毫秒肯定不卡。

设置300了，还是卡住了，做题时辅助没反应，我就自己答题，答到第三题辅助起作用了，然后就卡住了

**Comment by studyhelperhelper** [comment]
速度设置大3000或者更大。新手机应该没问题。识别速度的问题，暂时解决不了。
