### ISSUE TITLE
四人赛和双人赛 速度太慢了

### ISSUE THREAD

**Issue by snake636** [studyhelperhelper/studyhelper#322]
争上游能加快速度吗？基本都是输

**Comment by blackdarks** [comment]
关键是现在不知道怎么设置，我也发现更新后的答题往往要刷5-6次，太拖时间了，而且答案往往要错1次

**Comment by studyhelperhelper** [comment]
文字识别OCR本身比较吃CPU，旧手机识别慢，没办法，我的荣耀50pro 每次都第一名。
