### ISSUE TITLE
题库中有些答案是错的，而且不能更新错的题目。

### ISSUE THREAD

**Issue by ygfly** [studyhelperhelper/studyhelper#323]
一直有这个有这个感觉，这次终于验证了这个问题的存在。
如：有一道题“在中国古代兵器中，_____被称为“百兵之君”，也就是兵器之首。”  正确答案是“剑”    ，每次遇到这题都会答错，打开题库开关，下次遇到这题还是答错，题库不会更新！  当然题库肯定不是一道题是错的。

**Comment by ygfly** [comment]
一道关于“二十四史”的题，正确答案是“清史”，每次遇到这题都会答错。

**Comment by ygfly** [comment]
关于“遵义会议”的一道题，正确答案是“4”  ，每次都会答“6”   。

**Comment by ygfly** [comment]
“关于辐射”的一道题，每次遇到这题都会答错。

**Comment by ygfly** [comment]
征信机构对个人不良信息的保存期限，自不良行为或者事件终止之日起为（ ）年。
根据《征信业管理条例》，征信机构对个人不良信息的保存期限，自不良行为或者事件终止之日起为（ ）年。
这两道题答案都是5年，也是每次都错。

**Comment by ygfly** [comment]
“党的最大政治优势是密切联系群众，党执政后的最大危险是____。”   答案：脱离群众   ，也是每次都错。

**Comment by ygfly** [comment]
下列不属于二十四史的是：____二十四史有哪些？  答案：左传   ，也是每次都错。

**Comment by ygfly** [comment]
“根据《中华。。。。，警告标志放       米外。。。。。并且迅速报警。”  这题答案应该是150米，每次都会答100米。

**Comment by ygfly** [comment]
选择词语的正确词形   正确答案是：声呐  每次都会选  声纳

**Comment by ygfly** [comment]
“我国宪法规定。。。。。。过半数通过”   正确答案是三分之二，每次都会答四分之三。

**Comment by Kky0125** [comment]
哇塞，楼上的都记住题目了，赞一个。我最近的感觉是答案的顺序是随机变化的，比如说，以前的判断题，a是正确，b是错误，现在是题干不变，但b是正确，a是错误，会不会是制作题库的时候，设定是a正确，识别题干后，选择a，但是现在答案顺序变化了，所以不能判定正确或错误？？    所以我现在都不参与2人和4人的答题，能够自动完成其他项目，我已经很知足了。如果开发者看到了，请给个打赏方式，我想表表心意。感谢。

**Comment by studyhelperhelper** [comment]
已更新题库，关闭了。
