### ISSUE TITLE
米10s时间间隔怎么设置呢？

### ISSUE THREAD

**Issue by lxxy584604730** [studyhelperhelper/studyhelper#324]
我用的米10s识别慢，有时不识别，四人赛答完题后想再测试，无法进行。答题过程中如果嫌识别慢手动答题，后面大概率会卡主。希望能放开再次答题的权限。

**Comment by GarfieldR** [comment]
处理器太旧了，我的小米10ultra也是很卡很慢

**Comment by lxxy584604730** [comment]
> 处理器太旧了，我的小米10ultra也是很卡很慢

870的处理器不算旧吧，你说该用什么处理器合适呢

**Comment by twinklelucas** [comment]
835都用的飞起

**Comment by studyhelperhelper** [comment]
程序没那么智能，自动答题期间请不要触摸屏幕。可以再试试新版本。再答不对题就真的是识别速度的问题了。
