### ISSUE TITLE
双人和四人战次数有问题

### ISSUE THREAD

**Issue by SmileDeath233** [studyhelperhelper/studyhelper#327]
学习助手会多次进行双人和四人对战，即使积分已经拿到。

**Comment by studyhelperhelper** [comment]
故意的，别问了。说多了调整规则了，然而麻烦。

**Comment by zhouqingbiao** [comment]
我自己也写了一个apk，但是能力有限，截图使用了accessibility自带的截图，OCR这块使用tesstwo，很不理想，目前做成了，随机乱选四人和和双人，大佬能带带我嘛？
