### ISSUE TITLE
524更新到版本 下载地址不能用么？

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#342]

**Comment by wenrtxn** [comment]
估计还在更新中

**Comment by Hikarux1002** [comment]
> 估计还在更新中

已经离不开这个了 😄

**Comment by nihaolixin** [comment]
作者真伟大。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 中午11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [studyhelperhelper/studyhelper] 524更新到版本 下载地址不能用么？ (Issue #342)





  
估计还在更新中
  
已经离不开这个了 😄

**Comment by chskai** [comment]
点下载显示404

**Comment by Hikarux1002** [comment]
> 点下载显示404

还是不能下载

**Comment by blackdarks** [comment]
老版本不能用了，上来看看居然真更新了，现在推出release了

**Comment by MoneyInothe** [comment]
支持作者👍

**Comment by liuluo1979** [comment]
404

**Comment by Hikarux1002** [comment]
> 老版本不能用了，上来看看居然真更新了，现在推出release了

Release什么意思 可以下载了么

**Comment by Hikarux1002** [comment]
> 估计还在更新中

可以下载了么

**Comment by MoneyInothe** [comment]
不知道啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月24日 14:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [studyhelperhelper/studyhelper] 524更新到版本 下载地址不能用么？ (Issue #342) |

老版本不能用了，上来看看居然真更新了，现在推出release了

Release什么意思 可以下载了么

**Comment by Hikarux1002** [comment]
还是不能下载么

**Comment by qq549599389** [comment]
等大佬上架
