### ISSUE TITLE
最新版说再release中下载，哪位大佬说下如何下载

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#345]
作者页面介绍 请到release中下载 这个该如何操作  谢谢

**Comment by blackdarks** [comment]
估计大佬还没来得及发布

**Comment by wenrtxn** [comment]
https://raw.githubusercontent.com/studyhelperhelper/studyhelper/master/learningsudoku1.2.37.0-1.apk按这个地址下载了，提示404，不知道是不是地址问题

**Comment by yutongwangstudyhelper** [comment]
底下Releases显示
No releases published，不知道啥情况

**Comment by Scott19901203** [comment]
有了呀，可以下的

**Comment by nihaolixin** [comment]
直接点连接就能下载了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 中午11:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [studyhelperhelper/studyhelper] 最新版说再release中下载，哪位大佬说下如何下载 (Issue #345)





 
有了呀，可以下的

**Comment by Po2022** [comment]
大哥你看到的时候有了，我们看到时候还没有🌚



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月25日 11:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [studyhelperhelper/studyhelper] 最新版说再release中下载，哪位大佬说下如何下载 (Issue #345) |

有了呀，可以下的
