### ISSUE TITLE
这个新的1.3.8版本不如1.3.6版本

### ISSUE THREAD

**Issue by cherry845** [studyhelperhelper/studyhelper#35]
这个新版本答题全错，乱答一气，不一会儿还卡住不动了，还不如136版本，136版本虽然也会用一阵卡住，但至少在完成了20几分后才卡住，答题正确率在95%以上。幸好我保存了136版本的安装包！华为P10P用户亲测。

**Comment by 85524365** [comment]
同感那，会不会是输入法或题库的原因吧

**Comment by liangxyz** [comment]
我1.3.6和1.3.8都一样乱答题，郁闷

**Comment by liangxyz** [comment]
另外请问能分享下1.3.6版本吗？@cherry845

**Comment by studyhelperhelper** [comment]
原因是学习强国做了一个小改动，导致助手不能正确动作，下一个版本进行修订。至于答题出现全都不对的情况，是题库被意外清理了，请自行查找被意外清理的原因。或者发现被清理后重新安装。

**Comment by orangexw** [comment]
感谢分享！

**Comment by clyduke** [comment]
> 原因是学习强国做了一个小改动，导致助手不能正确动作，下一个版本进行修订。至于答题出现全都不对的情况，是题库被意外清理了，请自行查找被意外清理的原因。或者发现被清理后重新安装。

感谢大佬！

**Comment by gzhjic** [comment]
感谢大佬。
