### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by laoqiuqiu** [studyhelperhelper/studyhelper#351]
阅读文章时长可以和视频学习时长合并，就是先去“电台”，"听广播"中随便选一个，然后返回开始阅读文章时长的操作，这样阅读文章时长积分获取完毕视听学习时长也完成了，视频学习可以去"百灵"里面，上划就可以下一个视频了。这样速度会比以前快很多。

**Comment by blackdarks** [comment]
嗯，我也想提这个事呢，效率上讲你说的这个很效率
