### ISSUE TITLE
题库中还是有一些错题啊。

### ISSUE THREAD

**Issue by ygfly** [studyhelperhelper/studyhelper#352]
本人p30作为答题手机，答错一道题基本上就会输了比赛，所以对错题比较敏感，上次提出这个问题后，题库确实有了很大改善，修正了大量错题，但一直觉得还是有错题，今天终于被我抓住一道：
唐朝上元初年(公元760年)，陆羽隐居苕溪，撰成（ ）三卷，成为世界上第一部茶叶专著。正确答案是 茶经，但答题时有时会答成茶道，有时会答成茶曲。
盼望能彻底修正题库中有错题的情况。

**Comment by fjyl001** [comment]
是啊，现在基本四人赛都是垫底啊，双人对战还不错。题库可与https://github.com/mondayfirst/XXQG_TiKu上进行核对一下，上面的题库基本没有问题，而且更新也很快
