### ISSUE TITLE
这个项目有公开源代码吗？

### ISSUE THREAD

**Issue by nicegjj** [studyhelperhelper/studyhelper#353]
这个项目，我下载了source code 里面只有两个文件：output.json和readme.md。
这两个文件不是源代码。
请问作者公开源代码，供大家学习不？

**Comment by 15275037303** [comment]
> 这个项目，我下载了source code 里面只有两个文件：output.json和readme.md。
> 
> 这两个文件不是源代码。
> 
> 请问作者公开源代码，供大家学习不？

怎么操作呀哥
