### ISSUE TITLE
这个软的原理是什么？会被反外挂程序检测到吗？

### ISSUE THREAD

**Issue by awanghero** [studyhelperhelper/studyhelper#356]
这个程序是用OCR识别的吗？有没有变换原程序的逻辑？
有没有学友被检测封号的？
欢迎大家来交流

**Comment by PykeChen** [comment]
程序的原理就是利用Android的无障碍服务实现自动浏览、点击、跳转、翻页等等，这里面的细节逻辑还是很多的，而且还要去琢磨强国里面的UI逻辑等，所以还是要感谢作者的奉献。关于会不会被检测到的问题，基于无障碍辅助服务是模拟人的手势操作（不是通过接口直接调用），所以只要不要太非人类的操作基本上是不会检测出来的，收到这个，顺便提及下里面的一个细节：发表评论后会进行删除，也充分体现了。

**Comment by awanghero** [comment]
用了几个月了，确认解救了无辜dang外人等的宝贵时间

**Comment by awanghero** [comment]
8
