### ISSUE TITLE
强国更新了分数界面，导致不能用了

### ISSUE THREAD

**Issue by LvDeShei** [studyhelperhelper/studyhelper#359]
强国更新了分数界面，导致不能用了，大佬可以看看![IMG_20220901_225736_683.jpg](https://user-images.githubusercontent.com/49177549/187946343-00bc5e49-0ceb-4d55-90a0-9ce07433a2e2.jpg)

**Comment by ljtao020** [comment]
大佬很久没更新, 估计是放弃了

**Comment by nihaolixin** [comment]
能用的啊，你为什么不能用？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 中午11:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [studyhelperhelper/studyhelper] 强国更新了分数界面，导致不能用了 (Issue #359)





 
大佬很久没更新, 估计是放弃了

**Comment by ygfly** [comment]
你这是被检测到第一次违规，给与的警告。

**Comment by lls1043** [comment]
暂时不要升级学习强国，原来的能用

**Comment by studyhelperhelper** [comment]
已更新
