### ISSUE TITLE
App更新了，软件不能用了，求作者大大更新

### ISSUE THREAD

**Issue by nihaolixin** [studyhelperhelper/studyhelper#361]
求作者大大更新软件。app更新了。

**Comment by Bzxdh** [comment]
同求作者更新，感谢。

**Comment by realbbits** [comment]
装回旧版本

**Comment by nihaolixin** [comment]
有旧版本的APP吗？现在都找不到了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月21日(星期三) 中午1:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [studyhelperhelper/studyhelper] App更新了，软件不能用了，求作者大大更新 (Issue #361)





 
装回旧版本

**Comment by realbbits** [comment]
https://www.wandoujia.com/apps/7920908/history
随便搜索下就有……

> 有旧版本的APP吗？现在都找不到了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月21日(星期三) 中午1:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [studyhelperhelper/studyhelper] App更新了，软件不能用了，求作者大大更新 (Issue #361) 装回旧版本 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**Comment by studyhelperhelper** [comment]
已更新
