### ISSUE TITLE
卸载最新版本 安装对应的旧版本

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#368]
https://www.wandoujia.com/apps/7920908/history
在这里下载对应的版本 就是每次开启软件手动点一下不要升级
坐等作者更新

**Comment by Hikarux1002** [comment]
只找到市场里面 关闭了自动更新 不知道软件本身会不会自动更新

**Comment by awanghero** [comment]
找到应用权限，把强国的存储权限关掉，防止它在后台自己偷偷更新。

**Comment by jiurou** [comment]
> 找到应用权限，把强国的存储权限关掉，防止它在后台自己偷偷更新。

一直不知道怎么关闭自动更新，原来关掉存储权限就行了啊，感谢！

**Comment by studyhelperhelper** [comment]
下载2.41.0版本，关闭更新。可以正常使用。新版本目前没找到解决方案。

**Comment by studyhelperhelper** [comment]
已更新
