### ISSUE TITLE
2.37版本已经不让使用了，必须得更新app了，，大佬，跟进一下吧

### ISSUE THREAD

**Issue by cq4080** [studyhelperhelper/studyhelper#373]
2.37版本已经不让使用了，必须得更新app了，，大佬，跟进一下吧

**Comment by hzjdak** [comment]
顶上去，一直要求更新。。。。

**Comment by Bzxdh** [comment]
帮你顶顶，寻求大佬更新

**Comment by ygfly** [comment]
有没有办法屏蔽版本的检测呢？

**Comment by hzjdak** [comment]
> 有没有办法屏蔽版本的检测呢？

没办法，只要点击答题就要求更新。我现在把答题都关了，还能每天学个25分左右。

**Comment by GaviTate** [comment]
@studyhelperhelper 2.37版原来从“我要答题”进入已经失效，要求更新APP。建议答题入口改为从分数即每日任务清单进入（目前还有效）。

**Comment by zi0n8** [comment]
大佬更新一下吧

**Comment by xiangyun592** [comment]
大佬求更新，2.37.0已经不让用了。我心疼我爸妈，不忍心让他们整天就抱着手机刷xuexi强国，拜托大佬了！

**Comment by studyhelperhelper** [comment]
已更新
