### ISSUE TITLE
鸿蒙系统一直在反复开屏幕朗读

### ISSUE THREAD

**Issue by GarfieldR** [studyhelperhelper/studyhelper#378]
鸿蒙手机一直在打开屏幕朗读呢

**Comment by hh54188hh** [comment]
vivo也是，不知道是不是黑白的原因

**Comment by Ruru7788** [comment]
小米也是，开始学习后就打开屏幕朗读

**Comment by studyhelperhelper** [comment]
由于2.43版本无法点击到“我的”——菜单下的“学习积分”和“我要答题”两个选项卡，研究发现打开talkback,屏幕朗读后能够点击到，所以程序中加入了打开talkback屏幕朗读，为避免频繁打开，请尽量使用2.43.0以下版本。

**Comment by awanghero** [comment]
为了防止更新，记得关闭强国应用的读写权限，这样就不能在后台偷偷更新了

**Comment by Hikarux1002** [comment]
> 由于2.43版本无法点击到“我的”——菜单下的“学习积分”和“我要答题”两个选项卡，研究发现打开talkback,屏幕朗读后能够点击到，所以程序中加入了打开talkback屏幕朗读，为避免频繁打开，请尽量使用2.43.0以下版本。

大佬 不要用最新版本是么

**Comment by Ruru7788** [comment]
> 由于2.43版本无法点击到“我的”——菜单下的“学习积分”和“我要答题”两个选项卡，研究发现打开talkback,屏幕朗读后能够点击到，所以程序中加入了打开talkback屏幕朗读，为避免频繁打开，请尽量使用2.43.0以下版本。

感谢大佬

**Comment by TanningR** [comment]
> 由于2.43版本无法点击到“我的”——菜单下的“学习积分”和“我要答题”两个选项卡，研究发现打开talkback,屏幕朗读后能够点击到，所以程序中加入了打开talkback屏幕朗读，为避免频繁打开，请尽量使用2.43.0以下版本。

我的旧华为Play（鸿蒙2）无障碍下有”“TalkBack”选项，而华为Mate 30（鸿蒙3）相同位置相同功能叫做“屏幕朗读”。Play运行没问题，而Mate 30一直无法自动选到“屏幕朗读”。我猜和两个功能名称不同有关，供大佬参考。

**Comment by f524502657** [comment]
华为mate 30 鸿蒙OS 3.0，一直在设置屏幕朗读界面。
