### ISSUE TITLE
新版本一直朗读屏幕，各位是这样子么

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#379]
启动就是提示朗读屏幕 无限循环 是哪里出问题了么？

**Comment by studyhelperhelper** [comment]
并不会一直循环，是每次需要点击学习积分时。和每次需要点击我要答题时，都会打开屏幕朗读。由于2.43版本无法点击到“我的”——菜单下的“学习积分”和“我要答题”两个选项卡，研究发现打开talkback,屏幕朗读后能够点击到，所以程序中加入了打开talkback屏幕朗读，为避免频繁打开，请尽量使用2.43.0以下版本。
