### ISSUE TITLE
由于单位只要求至少30分，我把学习文章和视频总时长开关关掉了，但是发现几个问题： 1.挑战答题答第一二遍答不对5个，没分，第三遍答对7个得3分。之后就退出不答了。 2.每日答题15道题答错一道题只得到5分。也是就直接退出不答了。 3.文章和视频学习次数太多了，要打开20个左右视频和20个左右的文章，有点占用时间。如果是担心刷到重复的导致没分，视频可以刷百灵视频，每次刷都是不同样的。

### ISSUE THREAD

**Issue by wz960413** [studyhelperhelper/studyhelper#38]
由于单位只要求至少30分，我把学习文章和视频总时长开关关掉了，但是发现几个问题：
1.挑战答题答第一二遍答不对5个，没分，第三遍答对7个得3分。之后就退出不答了。
2.每日答题15道题答错一道题只得到5分。也是就直接退出不答了。
3.文章和视频学习次数太多了，要打开20个左右视频和20个左右的文章，有点占用时间。如果是担心刷到重复的导致没分，视频可以刷百灵视频，每次刷都是不同样的。

**Comment by noway2014** [comment]
为何每一次升级都存在问题，而且似乎都是同样的问题？没有解决

**Comment by wz960413** [comment]
只能寄希望于作者尽量解决，因为他也不是专业的程序员。而且又是免费发布这款程序。要求不了很多。
