### ISSUE TITLE
助手2.43版搭配QG APP的哪个版本更好用啊

### ISSUE THREAD

**Issue by GaviTate** [studyhelperhelper/studyhelper#381]
@studyhelperhelper 助手更新到2.43版，APP保留原2.37版：执行任务时进入答题环节还是弹更新窗，不能进入答题任务呢
助手能否从积分任务列表进入答题，或者说搭配APP的哪个版本能比较完整的完成任务呢

**Comment by hzjdak** [comment]
我现在用的是2.40版本，刚进APP会弹窗，但是答题是正常的。

**Comment by lls1043** [comment]
2.41正常
