### ISSUE TITLE
四人对战与双人对战不答题

### ISSUE THREAD

**Issue by GOOD-AN** [studyhelperhelper/studyhelper#382]
四人对战进入后完全不作答。
双人对战在匹配页面一直弹出是否退出的界面，即使手动点击随机匹配后，依旧不作答。
其余任务正常。
手机为华为nova 7 5G版。
系统为鸿蒙，版本号为2.0.0.275。
答题软件版本为2.43.0。
QG软件版本为2.40.0~2.43.0，该段版本均出现上述问题。

**Comment by NYC361** [comment]
我也遇到了这个问题，手机为红米，系统为miui13,0.14

**Comment by 1to99** [comment]
> 你自己都发现问题了，2.40.0~2.43.0版本均出错。答题软件版不支持滑动验证，唉。
学习APP版本 v2.34.0以上不支持订阅、不要用 省电模式、不要升级 安卓12(特别是MIUI13) 、不要用 模拟器！v2.40.0以上限制截图 无法识别多人对战，勿升级。
最佳版本是2.33，但是会频繁弹出升级提示，不能看得分。
希望能在2.33版本基础上，去除升级提示或者用户手动输入版本号，欺骗系统。
安卓app那么多软件都能破解，何况QG乎。

> 四人对战进入后完全不作答。 双人对战在匹配页面一直弹出是否退出的界面，即使手动点击随机匹配后，依旧不作答。 其余任务正常。 手机为华为nova 7 5G版。 系统为鸿蒙，版本号为2.0.0.275。 答题软件版本为2.43.0。 QG软件版本为2.40.0~2.43.0，该段版本均出现上述问题。

**Comment by GOOD-AN** [comment]
> > 你自己都发现问题了，2.40.0~2.43.0版本均出错。答题软件版不支持滑动验证，唉。
> > 学习APP版本 v2.34.0以上不支持订阅、不要用 省电模式、不要升级 安卓12(特别是MIUI13) 、不要用 模拟器！v2.40.0以上限制截图 无法识别多人对战，勿升级。
> > 最佳版本是2.33，但是会频繁弹出升级提示，不能看得分。
> > 希望能在2.33版本基础上，去除升级提示或者用户手动输入版本号，欺骗系统。
> > 安卓app那么多软件都能破解，何况QG乎。
> 
> > 四人对战进入后完全不作答。 双人对战在匹配页面一直弹出是否退出的界面，即使手动点击随机匹配后，依旧不作答。 其余任务正常。 手机为华为nova 7 5G版。 系统为鸿蒙，版本号为2.0.0.275。 答题软件版本为2.43.0。 QG软件版本为2.40.0~2.43.0，该段版本均出现上述问题。

首先没有滑动验证的问题，这个是不存在的，还有我用过很多插件，滑动验证我只见过在 v2.40.0以下的版本，运行答题必触发滑动验证，而且确实写着 v2.40.0以上限制截图，但是，本软件最新版本第一次安装时使用完全没有问题，四人和双人正常，但是第二天就无法答题了，那时候还用的是QG版本还是 v2.41.0。

**Comment by GOOD-AN** [comment]
嗯。。。刚刚我的回复提醒了我，卸载重新安装后回复正常。
