### ISSUE TITLE
四人对战一直在循环挑战

### ISSUE THREAD

**Issue by lin-bin** [studyhelperhelper/studyhelper#384]
前两次挑战直接满分了，结果后面一直在继续四人挑战不退出。
手机华为nova9，鸿蒙3系统

**Comment by SheepKang** [comment]
我荣耀V20也有同样的问题，一直卡在四人赛。

**Comment by zglhappy** [comment]
是这样的，学习强国的四人对战的获胜情况会根据你的胜负率进行调整，例如如果你一直都是第一名， 那么会给你匹配到更难的对手。所以程序设计一般都是前两局获胜，然后后两局0分，是为了下次能更好的获胜。

**Comment by lee-yong** [comment]
P30也有相同问题，可以代码开源吗？
