### ISSUE TITLE
刷题库开启

### ISSUE THREAD

**Issue by lin-bin** [studyhelperhelper/studyhelper#386]
之前我使用2.43版本，将刷题库开关开启后就会一直进行刷题，是正常的。但是我现在使用2.40版本后，启动刷题库，它不开始刷题，又跑去学习了，但是我今日学习的积分已满了，请问使用哪个版本的app要最好啊。

**Comment by hzjdak** [comment]
我用的2.40一直挺好 ，刚打开的时候偶尔会提示更新，关掉就好了

**Comment by awanghero** [comment]
刷题库开关开启打开是不是四人赛会多刷两轮。没看到有什么刷题行为啊？现在比赛老是答错题，怎么回事？
