### ISSUE TITLE
各位还能用吗

### ISSUE THREAD

**Issue by shaozongjie** [studyhelperhelper/studyhelper#392]

**Comment by fsdsoyu** [comment]
2.33被警告了

**Comment by lahongde** [comment]
老版本弹更新，用不好

**Comment by nihaolixin** [comment]
我用的时2.41



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月11日(星期二) 晚上10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [studyhelperhelper/studyhelper] 各位还能用吗 (Issue #392)





  
2.33被警告了
  
用了那么多年终于检测到了？

**Comment by dmmxxq** [comment]
已经被封号了

**Comment by hzjdak** [comment]
我用的2.40，关闭了每日答题、双人对战，目前良好。

**Comment by hzjdak** [comment]
> 已经被封号了

你被封号前有消息提醒吗？

**Comment by dmmxxq** [comment]
没有任何提醒，就土壤说违规了，禁止登录




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月12日(星期五) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [studyhelperhelper/studyhelper] 各位还能用吗 (Issue #392)





  
已经被封号了
  
你被封号前有消息提醒吗？

**Comment by nihaolixin** [comment]
你多少分被封的？是不是异地登入或者干什么了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [studyhelperhelper/studyhelper] 各位还能用吗 (Issue #392)





 没有任何提醒，就土壤说违规了，禁止登录 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年5月12日(星期五) 上午10:27 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [studyhelperhelper/studyhelper] 各位还能用吗 (Issue #392) 
 
 
 
 
 
    
 已经被封号了 
    
 你被封号前有消息提醒吗？
