### ISSUE TITLE
各位vivo x90 pro可以用么

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#393]
一直在答题时候会来回跳答案 有办法解决么

**Comment by nihaolixin** [comment]
建议用安卓12版本的手机下4.1版本的qg软件。不要用13版本的安卓系统，对这个不是很友好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月13日(星期六) 凌晨0:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[studyhelperhelper/studyhelper] 各位vivo x90 pro可以用么 (Issue #393)





 
一直在答题时候会来回跳答案 有办法解决么
