### ISSUE TITLE
各位今天的正常么

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#395]
一直莫名卡住，双人答题，一直在开始界面，关掉了也会进去这个界面就卡住，挑战和每日答题也不做了 大家有这种情况么

**Comment by Jesse2021111** [comment]
今天开始，1V1和1V4不答题了

**Comment by nihaolixin** [comment]
是的，我也不行了，求大佬更新



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月30日(星期二) 上午10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [studyhelperhelper/studyhelper] 各位今天的正常么 (Issue #395)





 
今天开始，1V1和1V4不答题了

**Comment by lunarwater** [comment]
不能正常答题了 停在双人赛页面不动 求大佬更新

**Comment by lls1043** [comment]
1V1和1V4不自动答题，需要手动点击后才开始答题。

**Comment by Hikarux1002** [comment]
> 

双人手动点了会自动答题，四人手动点进去不会自动答题，还有挑战完全不去点了
