### ISSUE TITLE
更新了5.31和2.46.0版本，依旧不工作

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#397]
各位是这样子么💔

**Comment by Hikarux1002** [comment]
> 我也只能刷1分



> 我也只能刷1分

不是很懂了 软件也没更新，界面也没改变，为什么突然就不行了

**Comment by Hikarux1002** [comment]
没发现 作者大大已经更新了😄

**Comment by lierlvy** [comment]
一样，一直反复进出软件，一直只有一分

**Comment by Hikarux1002** [comment]
> 一样，一直反复进出软件，一直只有一分

看来还有bug

**Comment by Meepooown** [comment]
我也是  挂了2小时也操作  一直是反复进积分页面

**Comment by Iscroo** [comment]
一直反复进入积分界面。貌似是今天取消了双人四人答题计分，学习积分页面看不到了，挑战答题计分方式也调整了，不知道是不是和这个有关

**Comment by Hikarux1002** [comment]
> 一直反复进入积分界面。貌似是今天取消了双人四人答题计分，学习积分页面看不到了，挑战答题计分方式也调整了，不知道是不是和这个有关
刚发现这个改变

**Comment by studyhelperhelper** [comment]
学习强国修改了规则，我尽快更新。

**Comment by Hikarux1002** [comment]
> 学习强国修改了规则，我尽快更新。



> 学习强国修改了规则，我尽快更新。

🙏🫡

**Comment by xieqing1983** [comment]
好人一生平安

**Comment by 20057842** [comment]
好人一生平安

**Comment by beijubojue** [comment]
好人一生平安
