### ISSUE TITLE
建议分享采用qq（申请也方便）或者短信等

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#4]
因为微信对应手机号码，申请比较严格，建议大侠在分享的时候采用比较好申请的qq，或者手机上都有的短信分享。
      同时由于不同的手机设置不同，为了避免卡机，建议把分享功能设置到软件进程的最后一步，到时候即使分享出错也不怕，因为能学习的基本都学习完了。

**Comment by studyhelperhelper** [comment]
好的，研究一下。

**Comment by 85524365** [comment]
> 好的，研究一下。每个过程都是随机的，主要为安全考虑。尽量保持随机特性把。

大侠，建个电报或者qq群吧，可以及时学习反馈

**Comment by 85524365** [comment]
我的名字就是qq，方便的话可以加我吗？
