### ISSUE TITLE
作者大大，我不知道我发现的对不对，是不是现在的界面和平时不一样。

### ISSUE THREAD

**Issue by nihaolixin** [studyhelperhelper/studyhelper#400]
因为现在双人赛是只有星期三和星期六是给积分的，平时是没积分的，所以是不是只有星期六和星期三会出现双人赛，平时的话是隐藏在我要答题那一板块的。我不知道是不是这样设定的。

**Comment by Hikarux1002** [comment]
昨天出现挑战 没有双人和四人  估计以后特定天出特定答题

**Comment by nihaolixin** [comment]
那就是了，那这样就比较麻烦了，我不是专业的，假如在启动软件的时候加个时间验证行不行，比如今天星期六，那就是双人有积分就运行双人赛，平时是挑战赛就运行挑战赛。平时双和四都没分数了，还是说四人赛也会在特定时间给分数。

**Comment by Hikarux1002** [comment]
> 那就是了，那这样就比较麻烦了，我不是专业的，假如在启动软件的时候加个时间验证行不行，比如今天星期六，那就是双人有积分就运行双人赛，平时是挑战赛就运行挑战赛。平时双和四都没分数了，还是说四人赛也会在特定时间给分数。

看了更新公告，双人 四人 赢了10分 输了8分 差了两分 要么自己手动操作下得了

**Comment by studyhelperhelper** [comment]
已更新
