### ISSUE TITLE
强国6月2日更新了

### ISSUE THREAD

**Issue by MickeyDonaldMouse** [studyhelperhelper/studyhelper#401]
强国6月2日更新了
https://article.xuexi.cn/articles/index.html?art_id=8501197368201300194&item_id=8501197368201300194&reedit_timestamp=1685628584000&to_audit_timestamp=2023-06-01+22%3A09%3A44&study_style_id=feeds_default&pid=&ptype=-1&source=share&share_to=weibo

**Comment by nihaolixin** [comment]
这就难受了，每天不一样。

**Comment by aa331730417** [comment]
发了没？还是1分不会学习呀！大佬怎么破

**Comment by Hikarux1002** [comment]
不如答题手动弄  输赢就差2分

**Comment by beijubojue** [comment]
感觉规则过于复杂
要不作者大大就只弄一个自动阅读和视听的24分就好了+一个每日答题的功能就很满足了
其他订阅评论什么的，不太耗时间

**Comment by netover2022** [comment]
按照原来老版本，可以启动手动四人答题和双人答题以及抢答就好了

**Comment by studyhelperhelper** [comment]
已更新

**Comment by Hikarux1002** [comment]
> 已更新

感谢作者大大

**Comment by icdcom** [comment]
> 已更新

更新后的首开广告可以，点隐藏功能居然还一个不能跳过的30秒广告

**Comment by erlangzhang** [comment]
广告是不是过去恶心了，还要别人破解你这个app再发一个才能用吗
