### ISSUE TITLE
加了广告真恶心

### ISSUE THREAD

**Issue by erlangzhang** [studyhelperhelper/studyhelper#402]
恶心

**Comment by ming-eva** [comment]
要不你给作者捐钱？

**Comment by nihaolixin** [comment]
免费使用，作者想怎么加就怎么加，没必要这样吧。想想用了这么久了，作者也无偿在更新，想用就用，不想用就别用，没必要阴阳怪气的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 下午4:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [studyhelperhelper/studyhelper] 加了广告真恶心 (Issue #402)





 
要不你给作者捐钱？

**Comment by hzjdak** [comment]
爱用用，不用滚。
