### ISSUE TITLE
搞一个广告，软件就变质了

### ISSUE THREAD

**Issue by chencym** [studyhelperhelper/studyhelper#407]
搞一个广告，软件就变质了
路由器用了去广告，直接就登录不了了。
作者是有多缺钱才整个广告进去。

**Comment by Jesse2021111** [comment]
有一说一，大佬付出劳动，加个广告怎么了？看不惯建议弃用……又白嫖又BB，别把别人的好心，当成理所应当

**Comment by wenrtxn** [comment]
白嫖习惯了，把自己当大爷了，作者有义务为你做软件么？真恶心，加个不犯法的广告还是支持的

**Comment by ming-eva** [comment]
你清高，你捐给作者10万，他就不加广告了。
能做到吗？

**Comment by chencym** [comment]
各位说的对。我不用了

**Comment by dsus4wang** [comment]
又穷逼事又多
