### ISSUE TITLE
请问过程中会出现滑动验证怎么解决？

### ISSUE THREAD

**Issue by xdzhu** [studyhelperhelper/studyhelper#408]
使用过程中，尤其是一些答题之后提交的时候，会弹出来那个滑动的验证，如果不人为滑动过着验证的话，就一直网络错误，网络错误，最后失败。

目前软件能自动通过这个验证吗？

**Comment by J-Mully** [comment]
https://github.com/J-Mully/TechXueXi
可过滑动验证，一机多号
