### ISSUE TITLE
总卡死在发表一个观点后，建议在发表观点后，增加一个判断语句。建议分享后加一个判断语句。

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#41]
一、总卡死在发表一个观点后，估计是输入法的原因，发表第一个观点后，屏幕闪了一下，好像关掉了个窗口，然后卡死。
可是我的输入法也是华为自带百度输入法呀。难道会是安卓8和安卓9的原因。
建议大神，在发表观点后，增加一个判断语句，如果回到发表观点窗口，就继续发表观点；如果没有回来，就再后退一步。
二、建议转发分享后加一个判断语句，如果没回到学习强国页面，则继续后退一步。这样即使微信没有登录也可以转发分享。

**Comment by kentmay** [comment]
我的手机上答题总是错误

**Comment by noway2014** [comment]
1.35-1.40没有一次完全正常过

**Comment by studyhelperhelper** [comment]
请问是发表观点，是点击  发布  按钮后不动了，还是点击删除，并且确定后不动了，我一直无法复现这个BUG。转发的我会在下一个版本增长判断条件。

**Comment by 85524365** [comment]
是在发表第一个观点之，而且软件能 确认删除了发表的观点，在这之后，就一直停留在该文章的底部，静止不动了

**Comment by 729748198** [comment]
这时候如果再点击一下发表观点，就会自动发一条并删除，然后返回，卡在文章列表页面
