### ISSUE TITLE
很少用了。感谢作者

### ISSUE THREAD

**Issue by sbwxwcf** [studyhelperhelper/studyhelper#415]
用了好几年，一直都很好用，现在规则变了，用这个还不如自己手工做了，而且又多了广告，体验不行了

**Comment by nihaolixin** [comment]
感谢作者，虽然我不用了，但是还是辛苦作者




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月24日(星期四) 下午2:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[studyhelperhelper/studyhelper] 很少用了。感谢作者 (Issue #415)





 
用了好几年，一直都很好用，现在规则变了，用这个还不如自己手工做了，而且又多了广告，体验不行了
