### ISSUE TITLE
悬浮窗功能可以去掉了

### ISSUE THREAD

**Issue by edwardmjc** [studyhelperhelper/studyhelper#42]
百度出来的结果你懂得， 都是不直接给你看， 引诱你点进去还要注册什么的。
建议改成某些专门出答案的网站。
比如http://xxqg.xyz/post/174.html，更新还挺快的。就那些答案放在html中而已。
如果启动软件前自动载入就好了。
感谢作者付出。

**Comment by 85524365** [comment]
就没用过这个功能

**Comment by studyhelperhelper** [comment]
好的，下一版本调整一下。

**Comment by LIUYUYANSZ** [comment]
这个主意不错，就是题库的地址经常更新。

**Comment by cherry845** [comment]
这个主意是真的不错，希望作者能跟进更新，谢谢，还有现在的这个版本还是喜欢卡住不动。
