### ISSUE TITLE
软件刚出时很好用，后来逐渐不好用了，就很长时间没用过了。

### ISSUE THREAD

**Issue by lxxy584604730** [studyhelperhelper/studyhelper#421]
可能是小米手机的问题吧。

**Comment by dsus4wang** [comment]
issue不是让你发这种没有意义的bullshit的

**Comment by lxxy584604730** [comment]
> 问题不是让你发这种毫无意义的废话
也不是废话，我反应了软件存在的问题，换句话说app在MIUI下运行不理想，主要是ocr识别问题。

**Comment by lxxy584604730** [comment]
> issue不是让你发这种没有意义的bullshit的

也不是废话，我反应了软件存在的问题，换句话说app在MIUI下运行不理想，主要是ocr识别问题。

**Comment by studyhelperhelper** [comment]
主要是没有测试资源，我找个小米的手机测试一下试试。
