### ISSUE TITLE
虚拟机运行没反应

### ISSUE THREAD

**Issue by superz77** [studyhelperhelper/studyhelper#423]
装了光子虚拟机和学习app2.50.0   运行没反应请问是怎么回事？辅助服务开了然后点开始学习，会跳转打开app，但是不会动，什么操作都没有

**Comment by studyhelperhelper** [comment]
已更新，大幅减少广告

**Comment by superz77** [comment]
正在努力加载中...http://user.qzone.qq.com/1535368015/
