### ISSUE TITLE
流氓广告

### ISSUE THREAD

**Issue by aa331730417** [studyhelperhelper/studyhelper#427]
无情广告

**Comment by aa331730417** [comment]
一直跳转安装，你说看广告吧，免费的嘛看就看吧，一直主动安装，连看广告的机会都没有

**Comment by Wind6666** [comment]
> 一直跳转安装，你说看广告吧，免费的嘛看就看吧，一直主动安装，连看广告的机会都没有

你好，请问你现在能看广告吗？我最近都显示广告数据为空，因此不能使用其功能了

**Comment by sanxian009** [comment]
┇兑付工作进行中，系统筛选到您未进行信息登记，可能会造成后续款项无法进行通知，请您尽快进行登记工作，登记员Q号：3471834176 备用：544411375 ┇ 2023年8月30日。

**Comment by studyhelperhelper** [comment]
已更新，大幅减少广告
