### ISSUE TITLE
连续几天广告数据为空，导致无法运行刷题。

### ISSUE THREAD

**Issue by lilei1980** [studyhelperhelper/studyhelper#429]
楼主大大，感谢你做的app，太方便刷题了。每天点击广告后，就可以正常做题，偶尔有些不顺畅，大部分时间都运行正常。可是，最近几天，广告数据为空导致无法使用其功能，卸载，重新安装仍然无法解决问题。完全不能使用了。拜托尽快解决和更新一下。

**Comment by laohuoji3030** [comment]
v:kun980617无广告适配最新版本

**Comment by studyhelperhelper** [comment]
已更新，大幅减少广告
