### ISSUE TITLE
ask questions

### ISSUE THREAD

**Issue by Jack-261108** [studyhelperhelper/studyhelper#444]
想请教一下解析数独图片功能是如何实现的？

**Comment by studyhelperhelper** [comment]
没听明白问题，提示功能中，在数独区域画的箭头虚线，圆圈等，是通过画布绘制的。
自定义数独中，根据照片或摄像头识别数独，是用的OCR

**Comment by Jack-261108** [comment]
> 没听明白问题，提示功能中，在数独区域画的箭头虚线，圆圈等，是通过画布绘制的。 自定义数独中，根据照片或摄像头识别数独，是用的OCR

大佬，就是在自定义数独中，是如何根据图片准确识别数独的，我也想实现这个功能。但是不知道如何实现，可否给个具体的具体的实现思路，我想借鉴一下。看了您仓库中的识别数独的项目，出现了小问题，导致识别的不是那么准确，我不知道如何解决，所以想参考参考

**Comment by Jack-261108** [comment]
> > 没听明白问题，提示功能中，在数独区域画的箭头虚线，圆圈等，是通过画布绘制的。 自定义数独中，根据照片或摄像头识别数独，是用的OCR
> 
> 大佬，就是在自定义数独中，是如何根据图片准确识别数独的，我也想实现这个功能。但是不知道如何实现，可否给个具体的具体的实现思路，我想借鉴一下。看了您仓库中的识别数独的项目，出现了小问题，导致识别的不是那么准确，我不知道如何解决，所以想参考参考

**Comment by Jack-261108** [comment]
大佬，就是在自定义数独中，是如何根据图片准确识别数独的，我也想实现这个功能。但是不知道如何实现，可否给个具体的具体的实现思路，我想借鉴一下。看了您仓库中的识别数独的项目，出现了小问题，导致识别的不是那么准确，我不知道如何解决，所以想参考参考
