### ISSUE TITLE
大神，请问安装目录在哪里

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#45]
首先感谢大神的无私奉献。
1、我这边，经常出现答题正确为0分的情况，好像是题库丢失，如果能把题库复制出来，丢失了再复制回去就方便了。最好出现新的题，自己也可以加进去，那就更完美了。
2、建议分享和发表观点，后做个判断语句，如果没有返回到应该回到的界面，就再重复一个back。

**Comment by studyhelperhelper** [comment]
data/data/包名/database下，我估计是在applicant中打开数据库导致的数据库丢失，正在测试什么时候用什么时候打开数据库，下一个版本修正一下。目前大家如果发现答不对题，请重新安装。关于不同手机分享和发表评论返回次数不一样的问题，我要找出返回界面的特征才好做判断，最近没分析。看看能不能修正吧。
