### ISSUE TITLE
1.4.3 卡在答题的环节

### ISSUE THREAD

**Issue by KerwinChen** [studyhelperhelper/studyhelper#50]
之前使用 1.4.2 的时候还好好的，升级了1.4.3后，会在某次答题的时候，一直重复点击查看提示，进行不下去下一步。使用的是 Android 7，学习强国应该是2.6.1

**Comment by 85524365** [comment]
我的学习强国程序是2.6.0，也是不行，也是反复点击提示查看，查看后就是不能确定选项，提示中有红色字体，例如 ：  南京长江大桥   那一个，经常出现。

**Comment by 85524365** [comment]
我这边从1.4.2就出现答题报错的现象了

**Comment by wenrtxn** [comment]
作者标注了适配2.60版本，2.61一样也不行
