### ISSUE TITLE
今天学习时，终于发现微信 只能分享1次 的错误原因了

### ISSUE THREAD

**Issue by 85524365** [studyhelperhelper/studyhelper#58]
感谢作者大爱，这次标题党一次，嘿嘿。

确实发现微信出现分享错误，导致不能进行下一步的情况了。

今天学习的时候，眼睛都不眨的，一直盯着屏幕，嘿嘿。都瞅花眼啦

发现当微信没有登录时，
分享时会出现登录微信界面，
然后调出了26字母的输入法界面，
待下一步返回时，仅仅把26字母的输入法界面去掉了，
仍然停留在微信登录界面，
不能back到新闻联播界面。

在此建议是否能增加一个while或if等判断语句，如果是返回到了刚才的视频界面，则继续分享。else则是微信登录界面，增加一个back。

**Comment by 85524365** [comment]
同理，发表观点也经常只能发表1个，删除之后立刻卡住。

而第二个观点，猜测也是安卓8导致的 ，是不是也增加一次输入法back判断语句呢？

**Comment by studyhelperhelper** [comment]
试试
