### ISSUE TITLE
作者能不能研究一下怎么把辅助挑战答题的当前连续答对数量显示出来？这样看到答对十个就可以退出了

### ISSUE THREAD

**Issue by wz960413** [studyhelperhelper/studyhelper#59]

**Comment by studyhelperhelper** [comment]
好的

**Comment by NATO2000** [comment]
> 好的

辅助答题你还想十个？现在辅助答题100次能做对5道题就是烧高香了，作者非说是什么覆盖安装题库掉了，我卸载完+清空数据+重新安装一样还是那副吊样子，有时候让他学1个多小时回头一看一分都没涨。

**Comment by wz960413** [comment]
#baiduhaokan://home/index/?channel=recommend&vid=13121135459386421144&auto_play_index=0&tab=guide&tag=web_wise&source=web_wise-0-1019957z&ext_content=%7B%22BAIDUID%22%3A%2223B7C79D9213A01FC508C89AB044734D%3AFG%3D1%22%2C%22vid%22%3Anull%2C%22cuid%22%3Anull%2C%22pd%22%3A%22web_wise%22%2C%22rec_sid%22%3A%22gr_sid_1%22%2C%22is_show_banner%22%3Atrue%7D&ctime=1572106909#第一，作者是无偿服务，说话不要充满责怪。第二，我遇到过你说的问题，但是重新安装后就好了，现在1.4.5版本可以连续答对几十道题中间不会错一道。都不需要百度了，优化的越来越好！不知道你的是什么情况。

**Comment by wz960413** [comment]
卡在了第二次评论，所以挑战答题也就没完成。其他都完成了。

**Comment by noway2014** [comment]
出问题的都在挑战和每日，能否单独出来做一个小程序。说实在的，从1.35到现在，没有一次能完全走完呀！
