### ISSUE TITLE
2.6.2-2版本，昨天还可以完成，今天就卡在了学习积分就无法自动操作了。

### ISSUE THREAD

**Issue by lzylzylhq** [studyhelperhelper/studyhelper#65]

**Comment by 85524365** [comment]
昨天晚上就卡在积分页面，进行不下去了，估计布局变化了！期待大神今天升级一下

**Comment by studyhelperhelper** [comment]
刚发现这个问题，有空看看。

**Comment by huuunm** [comment]
同样是这个问题

**Comment by smdk000** [comment]
对，我也是这个问题，然后重新打开辅助，提示没有开启下载权限，但是其实是已经开启了的！

**Comment by kentmay** [comment]
我是报告“学习助手已停止”，点击后就退出

**Comment by GitVanpen** [comment]
挑战答题助手也同样用不了了

**Comment by noway2014** [comment]
多次在积分面下停止运行问题

**Comment by 775226853** [comment]
> 刚发现这个问题，有空看看。

大佬 可否发一份源码给我呀

**Comment by aoyoo111** [comment]
我的也是卡在学习积分页面就不动了，华为mate 10 pro

**Comment by cheeshon** [comment]
源码不能给，死都不给

**Comment by 775226853** [comment]
> 源码不能给，死都不给

为什么？我就自己用 又不外传

**Comment by studyhelperhelper** [comment]
已更新

**Comment by huuunm** [comment]
> 已更新

又有新的问题，设置关掉每日答题和分享，运行应用的时候被还原了

**Comment by smdk000** [comment]
还有就是答题的时候，点进去了，然后第一题等很久，然后要么就直接返回了，要么就随便答一下，然后就返回了，测试了快2个小时一直是这个问题，到现在还没有正常答题！

**Comment by GitVanpen** [comment]
挑战答题有点问题

**Comment by smdk000** [comment]
发现个新问题，会卡订阅，点进去，然后退出来，一直重复，答题也是，进去之后，填空题，会秒点提示，然后秒关提示，然后一直重复！

**Comment by studyhelperhelper** [comment]
报出错信息的话，请尽量说明详细信息，如手机型号，Android版本，输入法，学习强国版本号，助手版本，等，方便能重现错误，才好修正。目前支持学习强国2.6.2版本，完美支持Android9。

**Comment by GitVanpen** [comment]
> 报出错信息的话，请尽量说明详细信息，如手机型号，Android版本，输入法，学习强国版本号，助手版本，等，方便能重现错误，才好修正。目前支持学习强国2.6.2版本，完美支持Android9。

Essential Phone PH1  Android 10.0 输入法Gboard 昨天完美41分，今天更新之后其他没问题，但是挑战答题无法自动答题，手动也搜不出来答案了。

**Comment by studyhelperhelper** [comment]
如果搜不到答案，应该每日答题和挑战答题一起有问题。卸载重装，明天再试试看，再有问题再说。

**Comment by noway2014** [comment]
新的版本还是运行就出错，提示重新打开，强国版本是2.6.2

**Comment by 84471559** [comment]
新版本正常使用
