### ISSUE TITLE
无法下载了，这个项目下的下载链接似乎被屏蔽了！

### ISSUE THREAD

**Issue by NATO2000** [studyhelperhelper/studyhelper#67]
360浏览器点击下载没反应 ，我自己找个魔法上网试试

**Comment by NATO2000** [comment]
大家不用试了，被长城防火墙封禁了，我找个了免费的魔法上网把最新3号版本下载下来了。

最新3号版本操作正常，虽然不是特别顺利

**Comment by 84471559** [comment]
我直接在软件里点检查更新 可以升级

**Comment by huangbaolin** [comment]
> 大家不用试了，被长城防火墙封禁了，我找个了免费的魔法上网把最新3号版本下载下来了。
> 
> 最新3号版本操作正常，虽然不是特别顺利

大神有时间的时候能发一下吗？969042931@qq.com。万分感谢！！！

**Comment by noway2014** [comment]
开个电报吧，长期在这里也不是好地方

**Comment by 85524365** [comment]
> 我直接在软件里点检查更新 可以升级

我的点更新，直接退出了

**Comment by 84471559** [comment]
> 我直接在软件里点检查更新 可以升级
> 
> 我的点更新，直接退出了

我同事的安卓8 点更新也直接退出了
