### ISSUE TITLE
遇到问题

### ISSUE THREAD

**Issue by huuunm** [studyhelperhelper/studyhelper#74]
手机型号：红米5plus
系统版本：MIUI 10.3.2.0 稳定版，安卓 8.1.0
应用版本：强国 2.6.2，助手 2.6.2-3
问题描述：1.强国完成后第二天无法正常使用，需关闭辅助服务后重新打开，才能正常刷题。2.完成1操作后虽然能正常刷题但挑战答题功能失灵，大概率无法选到正确答案，手机重启后可能会恢复正常。3.会出现应用上划回到桌面的情况。4.设置内关闭的项目会重新打开。5.会出现即使关闭后台程序还在桌面执行某些操作。
建议反馈：1.设置一个悬浮的停止按钮。2.视频学习可以考虑在“百灵”上进行，设置6次10秒上划视频，等待18分钟退出。3.分享改为“分享到学习强国”直接返回也能获得积分，更为方便。

**Comment by NATO2000** [comment]
个人建议一旦出问题就重装，立马满血复活
