### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by s-mason** [studyhelperhelper/studyhelper#79]
每次动作间隔用随机数确定时间，操作顺序也用随机数打乱，防止系统检测。另外当前版本偶尔还会卡住。

**Comment by s-mason** [comment]
有些时候当天更新的新闻很少，刷新以后点击的新闻是以前点击过的，系统不算数。能不能判断字体是灰色的或者把看过的新闻ID存储在本地。

**Comment by studyhelperhelper** [comment]
少点就少点吧，残缺点也好，太好用了可能意味着封杀。

**Comment by KerwinChen** [comment]
> 少点就少点吧，残缺点也好，太好用了可能意味着封杀。

大佬有没有时间适配一下2.6.3？

**Comment by s-mason** [comment]
作者辛苦了。
