### ISSUE TITLE
真的很不明白，为何有时候又可有时候又不行？

### ISSUE THREAD

**Issue by noway2014** [studyhelperhelper/studyhelper#85]
2.6.2-3，经常走不完，有时候可以41，但是基本都不能走完，每日和挑战基本都不行，出错。卡着。
奇怪的是，既然是程序能运行，手机又没有变化，为何有时候可以，有时候不行呢？而且绝大多数都不行

**Comment by noway2014** [comment]
2.6.2-4又全部可以。过几天不知道又会不会不行了

**Comment by XueBab** [comment]
then stop using this and do it yourself, kid
