### ISSUE TITLE
挑战答题完全无法使用

### ISSUE THREAD

**Issue by icedog111** [studyhelperhelper/studyhelper#96]
挑战答题完全无法使用，作者是否更新下啊

**Comment by lukesijia** [comment]
多试几次就好了。有时候会连续答错几次。。。模拟真实答题也挺好

**Comment by tgbushack** [comment]
> 挑战答题完全无法使用，作者是否更新下啊

已经可以了

**Comment by icedog111** [comment]
连续20分钟未答完啊

**Comment by Orenkuo** [comment]
最近挑战答题错误率太高  1个小时基本都在反复答题  全部错误啊   请更新下  谢谢啦

**Comment by studyhelperhelper** [comment]
晚上挂上不管他，总能完成41分。刷多了，题库就有了。已开放刷题库开关，有时间的朋友可以刷刷，把题库分享出来。

**Comment by Orenkuo** [comment]
怎么分享题库呀  现在是有时间就把刷题库开关打开做挑战答题  正确率还是太低

**Comment by 85524365** [comment]
的确如此，感觉越刷题库，三小时下来，正确率也没怎么提高。
单纯的刷挑战答题，半小时下来，常卡在分享上，按理来说刷题库不应该出现分享的，这个分享不定时出现。

**Comment by 85524365** [comment]
> 晚上挂上不管他，总能完成41分。刷多了，题库就有了。已开放刷题库开关，有时间的朋友可以刷刷，把题库分享出来。

下午想单纯的刷挑战答题，本想一直刷下去，但半小时下来，常卡在分享上，按理来说刷题库不应该出现分享的，这个分享不定时出现。

**Comment by studyhelperhelper** [comment]
再解释一下，为调试方便，刷题课开关还有个调试功能，即打开刷题课开关，不管每一项是否满分都会再运行一次。所以刷题库的姿势是：刷挑战答题：打开刷题课开关，其他开关只保留挑战答题，挑战答题次数设置100次或更多，想刷多少次就设置多少次。正常使用时再设置回10次。

**Comment by studyhelperhelper** [comment]
已更新，不是题库的问题。

**Comment by Orenkuo** [comment]
感谢更新，辛苦啦！
