### ISSUE TITLE
请问大家定时开启软件学习怎么用的？我的设置夜间没开启。

### ISSUE THREAD

**Issue by imzen** [studyhelperhelper/studyhelper#98]

**Comment by XueBab** [comment]
把锁屏的所有设置去掉，就是按电源键就亮屏的那种，我现在是正常使用的

**Comment by noway2014** [comment]
没有锁屏，只是黑屏下，软件在后台。无法自动

**Comment by studyhelperhelper** [comment]
自动运行还不成熟，只是时钟到达定时的去唤醒，自动运行。经常后台被杀了就不能启动了。插上电源启动的概率高点。目前只设置了唤醒屏幕，向右滑动解锁。

**Comment by imzen** [comment]
好吧，当初建议作者开发定时启动也没想这么多，现在倒是想劝作者放弃开发定时启动了。这看起来不是一般的复杂。因为锁屏的关系。希望作者多在完善题库和其他功能上下功夫！感谢！

**Comment by 85524365** [comment]
去了也不行，不知道大神用的什么机型，想去买个同款的
