### ISSUE TITLE
能看autojs源代码吗

### ISSUE THREAD

**Issue by keep-an** [studyhelperhelper/studyhelper#99]

**Comment by 85524365** [comment]
见光死，你想害大家都没得玩吗？
大神，千万不要被这种无耻之人诱惑啦

**Comment by keep-an** [comment]
自己修改流程才能避免被发现，其实主要是看文章，答题太慢了

**Comment by lgxnas** [comment]
> 自己修改流程才能避免被发现，其实主要是看文章，答题太慢了

https://github.com/lgpersonal/LazyStudy
参考去改吧

**Comment by keep-an** [comment]
> > 自己修改流程才能避免被发现，其实主要是看文章，答题太慢了
> 
> https://github.com/lgpersonal/LazyStudy
> 参考去改吧

谢谢大神   代码我看过了  你的是用什么软件写的

**Comment by lgxnas** [comment]
> > > 自己修改流程才能避免被发现，其实主要是看文章，答题太慢了
> > 
> > 
> > https://github.com/lgpersonal/LazyStudy
> > 参考去改吧
> 
> 谢谢大神 代码我看过了 你的是用什么软件写的

是别人写的，不是Auto.js写的吗？Vscode上也可以写呀

**Comment by studyhelperhelper** [comment]
不是autoJS写的，就是一个javaAPP，为了大家能用，不公开代码了。
